### ISSUE TITLE
Not able to vote with the ARK wallet on custom networks.

### ISSUE THREAD

**Issue by NayiemWillems** [ArkEcosystem/desktop-wallet#1001]
**Platform (please complete the following information):**
 - All platforms
 - All versions up to 2.2.0

**Describe the bug**
When using the ARK wallet or cloning the ARK wallet for my own chain using the ARK codebase,
I'm not able to vote on v2 networks.
It is also not able to find peers when you restart the wallet unless you enter a custom peer.

**How to reproduce the bug**
Steps to reproduce the behaviour:
1. Add network or peer to your wallet.
2. Import or create wallet with funds.
3. Vote on any delegate.
4. The wallet button will be grey or the vote will be rejected.

**Expected behaviour**
Normally you will be able to vote for delegates with a successful tx. 

**Additional context**
I've solved this problem for our wallet (Qredit) but using other wallets will not work.

**Possible Bug**
When the wallet connects to a custom network, it should grab the information from the config in the root folder.
However, the network information is being pulled from;
> /node_modules/@arkecosystem/crypto
&
> /node_modules/@arkecosystem/client

The following modules are grabbing information from these packages;

> workers/bip38-worker.js:const { crypto } = require('@arkecosystem/crypto')
> store/modules/ledger.js:import { crypto } from '@arkecosystem/crypto'
> services/client.js:import { crypto, transactionBuilder } from '@arkecosystem/crypto'
> services/transaction.js:import { crypto } from '@arkecosystem/crypto'
> services/wallet.js:import { crypto, Message, validator } from '@arkecosystem/crypto'
> store/modules/peer.js:import apiClient from '@arkecosystem/client'
> services/client.js:import ApiClient from '@arkecosystem/client'

**Temporary fix for our wallet**
Change the following files with the config from our own network.
> node_modules/@arkecosystem/crypto/lib/crypto/crypto.js
> node_modules/@arkecosystem/client/lib/peers.js
> node_modules/@arkecosystem/client/dist/index.cjs.js

and published the package under a different name on npmjs library.

After that, I've replaced all the lines with @arkecosystem/crypto and @arkecosystem/client to our own.

**Comment by alexbarnsley** [comment]
There was a missing change in the ARK wallet release which currently doesn't impact mainnet or devnet nodes (since devnet has been told to not update to the current develop branch HEAD). We'll likely do a small release just to get this out there. The core version, assuming you based it off of the develop branch, will be looking for a different header than what the wallet is sending.

Perhaps there's a bug with the v1 endpoints and vote transactions.

I'll leave this open to confirm the above, but also look into the peers issue you're having.

**Comment by NayiemWillems** [comment]
I think you can close this one. Already fixed in 2.2.1 :)

Nice job.
