### ISSUE TITLE
Use vendorFieldLength value from core API config

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/desktop-wallet#1162]
**Is your feature request related to a problem? Please describe.**
The 2.3 core version has a vendorFieldLength property. This needs to be used for the send transfer transaction type in order to limit the length based on the network. The default can be 64.

**Describe the solution you'd like**
Pull the vendorFieldLength from the `/api/v2/node/configuration` API endpoint (if it exists) and use it to limit the length on the send screen. Otherwise default to 64 characters.

**Also need to properly test the valid bip39 passphrase check in the field**

**Comment by luciorubeens** [comment]
Closed via #1233
