### ISSUE TITLE
Ledger: The first argument must be one of type string, Buffer, ArrayBuffer, ...

### ISSUE THREAD

**Issue by boldninja** [ArkEcosystem/desktop-wallet#1169]
Opening an issue on behalf of Slack user _markus_

**Platform:**
 - OS: Windows 10
 - Version: Desktop Wallet v2.3.2

**Describe the bug**
In version 2.3.2 when you sent ARK to a new Ledger Wallet address, the funds arrive as normal. But when you try to vote or make some kind of transaction from the wallet, you will get the following error: "Could not sign transaction with Ledger: The first argument must be one of type string, Buffer, ArrayBuffer, Array....." When you try again in 5 minutes. it seems to work fine. 

He tried with different wallets and ledgers, same results.

When you change something in the fee, you get the same error bottom left.

You wait 10 seconds and click the button again ... It communicated with ledger and will work.

If you keep trying it will work without an error. But it could be enough for people to give up on it. Same issue on different machines but only with client 2.3.2

When he used an older version of the Desktop Wallet the issue is not present.

![image (92)](https://user-images.githubusercontent.com/25795454/55726081-48914500-5a0f-11e9-85e1-3ef11da79de4.png)

**Comment by luciorubeens** [comment]
:trollface: 

<img width="300" alt="typescript" src="https://user-images.githubusercontent.com/4539235/55727963-854a4580-59e9-11e9-88de-73899f88ff5a.png">

**Comment by boldninja** [comment]
:joy:

**Comment by j-a-m-l** [comment]
I've been able to reproduce on Linux too.
