### ISSUE TITLE
chore: update tailwindcss to version 1.x.x

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/desktop-wallet#1278]
It brings a couple of changes, so there is an [upgrade guide](https://tailwindcss.com/docs/upgrading-to-v1) available

**Comment by sebastiangseijo** [comment]
Hi, i want to take this one, first contribution

**Comment by alexbarnsley** [comment]
![Sounds good to me!](https://memegenerator.net/img/instances/58881946.jpg)

**Comment by alexbarnsley** [comment]
Set as refactor type as it requires some css changes

**Comment by sebastiangseijo** [comment]
Tomorrow i will have this finished i think

**Comment by alexbarnsley** [comment]
@sebastiangseijo how are you getting on with this?

**Comment by sebastiangseijo** [comment]
Hi, sorry for all the time it took, I was on vacation and with a lot of work, i'm 90% finished in this task

**Comment by alexbarnsley** [comment]
👀

**Comment by sebastiangseijo** [comment]
I will do PR today's night probably

**Comment by faustbrian** [comment]
Closing in favour of https://github.com/ArkEcosystem/desktop-wallet/issues/1933.
