### ISSUE TITLE
chore: update dependencies

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/desktop-wallet#1279]
Quite a lot of dependencies are outdated at the moment (Electron is at v5 now while we are on 3 for example).

**Comment by luciorubeens** [comment]
Last time I tried, I had compatibility issues with the [@ledgerhq/hw-transport-node-hid](https://github.com/LedgerHQ/ledgerjs/tree/master/packages/hw-transport-node-hid) package. Will check again.

**Comment by alexbarnsley** [comment]
@luciorubeens 	that package has been removed as of #1296 🤔

**Comment by luciorubeens** [comment]
I'm going to upgrade to Electron 5 and Node 12 after #1332.

**Comment by alexbarnsley** [comment]
:myman:

**Comment by alexbarnsley** [comment]
This is done imo, since Electron is 6, soon to be 7. @faustbrian was looking at 7 today. I won't keep this open as it's a "continuous" task.
