### ISSUE TITLE
offer possibility to start a node for greater privacy

### ISSUE THREAD

**Issue by fix** [ArkEcosystem/desktop-wallet#1293]
There is some privacy leak on desktop app, where a attacker node could match IP with accounts that are fetched by this IP. This could help the attacker to localise the owner of some wallets.

What could be possible to mitigate the issue is then to offer to spin up a full node and connect to it when it is sync.

Obviously since this can be power/space consuming, this is important to:
- assess the power of the host computer
- add a warning when the user has wallets accounting for ark amount > 1000 to advice to start a local node.

When the user agrees to start a full node, ideally it should
- ask if they want to spin a node to an external server (DO, Vultr, etc...)
- ask if they want to run locally.

Starting a node is relatively straightforward. Updating it might be more cumbersome. What can be node is a warning about new version by adding a new API on the core where the full node is regularly scanning for the network and detecting when most nodes are being updated, and then trigger the update method. Special care should be done to potential fishing attack using this vector

**Comment by alexbarnsley** [comment]
This is a major piece of work since it would require at least 1 additional core plugins to manage the core node from the wallet. It's also an extremely advanced feature so I wouldn't consider this to be built into the wallet directly, only as a plugin.

**Comment by fix** [comment]
yes, this can be a plugin, point is that it is a greater privacy enhancement so imho at some point it should interact with the user to propose this solution.
Obvioulsy, if you manage a few $100 within the wallets, this should also be hidden

**Comment by alexbarnsley** [comment]
I'm still not sure about this so I'll just mark it as a discussion point to see if anyone would use it. I don't think this would be developed by the team.
