### ISSUE TITLE
Migrate to stable release of @arkecosystem/client

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/desktop-wallet#1314]
The first stable release of https://github.com/ArkEcosystem/typescript-client has been published as `1.0.0` which includes a lot of breaking changes and the removal of `ark-node` API support.

Peer discovery logic has been moved to https://github.com/ArkEcosystem/typescript-peers.

**Comment by alexbarnsley** [comment]
Already in progress

**Comment by alexbarnsley** [comment]
this is done :success:
