### ISSUE TITLE
Discussion: Advanced options when sending transactions

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/desktop-wallet#1399]
@zillionn
>Have you thought about hiding the Smartbridge and Transaction fee fields and add a switch Advanced settings which will show them? 99% of the times users will not touch those 2 fields.

Copied from #1386

**Comment by zillionn** [comment]
I have this idea about the transfer popup. How about to have few steps:
1. `Transaction Type`
   - Transfer
   - Vote/Unvote
   - Reddit tip
   - Twitter tip
   - etc.
2. `Transaction details`
   - Sender
   - Recipient / Reddit username
   - Amount
   - etc.
3. `Sign & Send` - here you'll see and confirm all the data and show only 1 field at the bottom for the passphrase.

Step 1 & 2 could be combined but show different fields depending on the tx type.
