### ISSUE TITLE
Improve voting UX

### ISSUE THREAD

**Issue by angryturnip** [ArkEcosystem/desktop-wallet#143]
I'm not sure if this is intentional or not, but when I was trying to vote for a delegate for the first time, I searched for the delegate just fine, but then when it showed up I ran into a weird design choice. There's a check-mark next to it and one above (I'm assuming to check or uncheck all delegates you have listed there?). When I unchecked it, rather than what I assumed would happen (nothing aside from being unchecked), it deleted the delegate from the list and I had to search for it again. If that check mark is supposed to remove it from the list, it's not very clear at first glance.

**Comment by zillionn** [comment]
Well that's because it used to be possible to vote for more than one delegate.

I agree, the voting tab should be redesigned for ARK.

**Comment by fix** [comment]
agree on this UX issue.
The original idea is the following:
- if you unvote and then vote for somebody else, this is 2 transactions so cost is 2 arks.
- if you make the unvote + vote into the same transaction, it would cost only 1 ark.

So the UX try to optimise votes by:
- select the final list of votes into the client (no transaction sent)
- then commit to the blockchain when the user is happy (hitting the button "VOTE")

Hence when you uncheck the delegate that is not commited yet on the blockchain, it disappears from the list.

on UX point of view, i am happy if you can come up with some ideas on how to reflect the voting processus at best.

**Comment by fix** [comment]
updated title for better understanding
