### ISSUE TITLE
Display of vote transactions is a bit confusing.

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/desktop-wallet#146]
cgould [6:08 AM] 
Ok I read that. It just seems odd that the From and To address are the same in the confirmation dialog

Maybe the to field should be filled with "Delegate Vote" like it is in the explorer?

**Comment by fix** [comment]
This is a weird legacy from lisk/crypti at protocol level, where the To address is needed for vote transactions. Will be fixed at the upcoming protocol upgrade at ark-node repo.

**Comment by eugeneli** [comment]
For now, I just check if the transaction is a "vote" transaction and replace the label with "Delegate Vote" instead of showing your address twice.

https://github.com/ArkEcosystem/ark-desktop/pull/150
