### ISSUE TITLE
Implement BIP38

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/desktop-wallet#147]
I think we need to add some more functionality in order that it gets harder to not store the passphrase.

We get a lot of comments on reddit that the users did not store their passphrase.

It would really be helpful to come up with something for new users.

The risk that they do not store it when first playing around is much higher than someone gets it stolen.

**Comment by Arckanum1** [comment]
I think in some other Wallet, maybe it was Waves.... After giving you the phrase, it goes to the next step, which is asking you for the Phrase to be able to enter the wallet for the first time.
Also, maybe the address could be hidden after creating the wallet for the first time. And the only way to make the address show up, would be to enter the Phrase. (for first time only)
Something like this to make the user realise this is important info

**Comment by fileninja** [comment]
Actually there is a Dialog.. when you create a new account you have to put in some words of your passphrase to verify that you saved it. All ways of storing it, either for 1 Time or Forever, is a security Problem. We may can add an additional Popup Highlighting the Relevance of this step

**Comment by Arckanum1** [comment]
Ahh, thanks. It has been so long since I made acc, I forgot that

**Comment by Jarunik** [comment]
The problem with that dialog to enter passphrase again is that most just copy paste the passphrase over and then loose it.

**Comment by fileninja** [comment]
But there are 3 fields for word 3, 6 and 9. So you cant just Copy paste?

**Comment by fileninja** [comment]
So, what i just want to say is that the actual Design Decision is good to Not forget to Save the passphrase. The Best One is to Take Pen and Paper for this. We may can add an image (write it down) and add a Timer for going to the Next step.
But thats still Not a protection when you loose it.

**Comment by Jarunik** [comment]
Maybe remove copy paste possibility unless you ensble it in settings?

**Comment by zillionn** [comment]
@Jarunik It's already done and it'll be available in the next version.

**Comment by fix** [comment]
1. partially fixed with https://github.com/ArkEcosystem/ark-desktop/pull/116 as said in this thread
2. this is also related to BIP38 (https://bitcoinpaperwallet.com/bip38-password-encrypted-wallets/) that is not yet implemented on this wallet. Idea is to be able to export the wallet data encrypted by a master password. This is less secure, but likely enough for most people if they don't have a lot of holdings in their wallet.

**Comment by fix** [comment]
Renamed title of the issue for better tracking

**Comment by sleepdefic1t** [comment]
Hilarious and possibly relevant.

![fullsizerender](https://user-images.githubusercontent.com/7477456/28744590-2197a8a0-7432-11e7-9ec3-8c777dd65ff3.jpg)
