### ISSUE TITLE
Format option for wallet

### ISSUE THREAD

**Issue by N1ckGreek** [ArkEcosystem/desktop-wallet#148]
Add dd/mm/yyyy format option to the wallet.

**Comment by fix** [comment]
You mean in transactions list? 

I suggest to create a settings popup window panel (like manage networks), because now settings are getting quite crowded

**Comment by dafty-1** [comment]
Only America uses the current mm/dd/yyyy format. The rest of the world uses dd/mm/yyyy.

Suggestion to make dd/mm/yyyy as default and configuration to change this in settings popup.

**Comment by fix** [comment]
agree that would be a nice improvement.

**Comment by wilruns** [comment]
should just make the client follow user's PC date format
