### ISSUE TITLE
Use TOR request to preserve privacy

### ISSUE THREAD

**Issue by fix** [ArkEcosystem/desktop-wallet#1570]
The main security issue right now with this wallet is that a node is able to match relatively easily ips with address by carefully auditing the requests on the public api. It can thus give information about location and sometimes more.

In order to mitigate this, it is possible to integrate TOR so the ip of the user is obfuscating the IP for each request. This can be proposed as optin when amount in wallets are getting over a thresholds.

There are 2 main options:
- allow the user to setup a proxy (to a local installed TOR node) (like https://github.com/jamesacampbell/elector/blob/master/index.js#L3)
- use https://www.npmjs.com/package/tor-request for testing if a tor node is present and switching silently to use it.

**Comment by vulet** [comment]
I like the idea of SOCKS5 and have mentioned it earlier in the year in the public chats, tcpdumps are stupid simple. I would say instead of a threshold it would be more interesting to have it in the customize peer option. Following issue.

**Comment by faustbrian** [comment]
Will be addressed in 3.0 by https://github.com/ArkEcosystem/desktop-wallet/pull/2645 and some UI changes.
