### ISSUE TITLE
feature: allow minimizing of transaction modals

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/desktop-wallet#1603]
This will allow users to pause a transaction and come back to it later on (see #1556). It may also be a good idea to timeout the confirmation screen and force users to re-enter details (e.g. after 5 minutes)

The functionality for minimizing the window should already be there so we can use that as long as the UX makes sense.

**Comment by dated** [comment]
The current implementation for minimized modals is fine tuned only for the update modal, other modals don't work that great. A different approach would be to completely minimize the modal and only show the modal title, e.g.

![mini](https://user-images.githubusercontent.com/6547002/75623895-3e3fe280-5baf-11ea-83ff-40140ed5b0ae.gif)

A proper implementation would also need some refactoring in how modals and portals are handled, to allow multiple modals to be minimized at the same time.

**Comment by faustbrian** [comment]
Closing, no longer relevant for 3.0
