### ISSUE TITLE
bug: transaction pagination rows

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/desktop-wallet#1606]
**Expected Behavior**

When I change the amount of rows while being on a specific page of transactions, it should not show 0 transactions when I switch to a larger rows per page amount.

**Current Behavior**

When you switch from 10 rows per page to 50 rows per page while having paginated, you can run into an empty page.

**Possible Solution**

Don't show an empty page, either default to page 1 when switching or show the transactions you were at but with the new row count (e.g. if you were a tx 40 (4x 10) and switch to 50 rows, it can show tx 40-90)

**Steps to Reproduce (for bugs)**

1. Go to a wallet with multiple pages of transactions 
2. Set rows per page to 10 if it isn't already
3. Navigate to the next page a couple times
4. Switch rows per page to 50
5. Press "prev" to go back a page
6. End up with an empty page if you now surpass the amount of transactions the wallet has (for example there are 100 transactions, you were on page 8 first, then switching to 50 rows would try to fetch transactions 350-400 which don't exist). It also shows an incorrect transaction count in the pagination

10 rows:
<img width="276" alt="image" src="https://user-images.githubusercontent.com/35610748/72611663-fd577b80-392a-11ea-9258-402c581af340.png">

switched to 50 rows:
<img width="296" alt="image" src="https://user-images.githubusercontent.com/35610748/72611720-1e1fd100-392b-11ea-8f5d-ebbd417b8ac8.png">

**Comment by davimello28** [comment]
I was able to reproduce this issue. The only requirement that was different for me was that step 3 was done on the last page. Navigating some pages into the middle even if I already surpassed the number of transactions didn't work for me.

**Comment by dated** [comment]
>default to page 1 when switching

This sounds good imho.

**Comment by dated** [comment]
Fixed in #1612.
