### ISSUE TITLE
Not selecting an avatar returns a TypeError

### ISSUE THREAD

**Issue by davimello28** [ArkEcosystem/desktop-wallet#1613]
The smallest user flow into the app (Next > Next > Next)  returns a TypeError. 

**Expected Behavior**

No errors.

**Current Behavior**

Return errors. Restarting the wallet seems to make everything work as expected.

![image](https://user-images.githubusercontent.com/3607502/72849723-1a22e480-3c86-11ea-9895-ac60daa30100.png)

**Possible Solution**

Either select a default avatar, prevent users from starting the wallet without an avatar or accept starting without an avatar. 

**Steps to Reproduce (for bugs)**

1. Reset the configurations of your wallet (Config > Reset Data)
2. Main Screen from Onboarding > Click Next.
3. Skip
4. Provide a Profile Name.
5. Next
6. Next
7. Done
8. See the errors.  

**Your Environment**

- Version used: `develop` branch.
- Environment name and version : Firefor 72.0.1 
- Operating System and version: Debian 10

**Comment by davimello28** [comment]
It seems that `AppSidemenu` is called before finishing the request by the last step of `ProfileNew` page, when `session_profile` is still undefined. 

This happens right after `this.$store.dispatch('profile/create', this.schema)` is called. Meaning that the component is hearing for changes on the state before it is displayed to the customer. 

Need to check if this happens due to an incorrect phase to mount the `AppSidemenu`.

**Comment by brenopolanski** [comment]
Hey @davimello28 

Selecting an avatar when creating a new profile also returns the same errors.

The solution to this would be in the computed property `hasAnyProfile` (in the [App.vue](https://github.com/ArkEcosystem/desktop-wallet/blob/develop/src/renderer/App.vue#L157-L159) file).

Use:

```
hasAnyProfile () {
  return this.$store.getters['session/profile']
}
```

instead of:

```
hasAnyProfile () {
  return !!this.$store.getters['profile/all'].length
}
```

Then the component `<AppSidemenu />` is only rendered if there is a profile.
