### ISSUE TITLE
Initial request to /delegates inside localhost fails with no port, 404 and CORS block

### ISSUE THREAD

**Issue by davimello28** [ArkEcosystem/desktop-wallet#1619]
Right after creating a new wallet, an initial request is made to the `http://localhost/delegates?page=1&limit=100&orderBy=rank%3Aasc`. No port was specified, is using HTTP and returns 404.

![image](https://user-images.githubusercontent.com/3607502/72899660-39148b80-3d05-11ea-98c9-e686b251ef91.png)

**Possible Solution**

I see no reason why this request was made when the wallet boots up. No information about the delegates is displayed on the screen. 

**Steps to Reproduce (for bugs)**

1. Reset the wallet.
2. Do the minimal flow to the main screen.
3. Watch the devtools. 

**Your Environment**

- Version used: Last `develop` branch,
- Environment name and version (e.g. node.js v10.15.3): Node 12.12.0
- Operating System and version: Debian 10

**Comment by alexbarnsley** [comment]
I believe the underlying issue here may be that the profile doesn't connect to a peer as soon as the first profile is created. The wallet fetches delegates on profile load to keep a local updated list of all delegates
