### ISSUE TITLE
2.6 has some bugs on UI

### ISSUE THREAD

**Issue by davimello28** [ArkEcosystem/desktop-wallet#1631]
![image](https://user-images.githubusercontent.com/3607502/73231459-311e7680-415f-11ea-9ef2-d0925385fdbf.png)

**Your Environment**

- Version used: 2.6 branch.

**Comment by alexbarnsley** [comment]
@davimello28 would you mind opening them as separate issues, please

**Comment by alexbarnsley** [comment]
Actually no, leave it as is. They're related to the same transaction forms 👌

**Comment by alexbarnsley** [comment]
In fact, I've already fixed the Business Registration fee slider

**Comment by davimello28** [comment]
I just removed the other one.

**Comment by brenopolanski** [comment]
> In fact, I've already fixed the Business Registration fee slider

Fixed!

![Screenshot from 2020-03-03 13-49-53](https://user-images.githubusercontent.com/1894191/75798925-10e16900-5d56-11ea-9ef1-41380a25f7b6.png)
