### ISSUE TITLE
Verify ledger nano S/X is genuine

### ISSUE THREAD

**Issue by fix** [ArkEcosystem/desktop-wallet#1635]
Ledger nano includes a way to verify that the ledger key is not a fake or a compromised key.
This check is performed by ledger live, but not by the desktop application. The security vulnerability since people are using regularly ledger live to update firmwares or update ark application. However this does not prevent from a short term targeted attack.

Ideally desktop wallet should perform a check of the ledger once connected. Documentation is here:
https://ledger.readthedocs.io/en/latest/bolos/features.html#endorsement-application-attestation
TLDR:
-  integrate the ledger certificate used to sign the device certificate
- perform a request to verify the signed certificate

see examples in python here:
- https://github.com/LedgerHQ/blue-loader-python/blob/0.1.31/ledgerblue/verifyEndorsement2.py

Bonus point: open secure channel to communicate with ledger nano s so this cannot be intercepted by a 3rd part app able to listen bluetooth/usb communication, see https://github.com/LedgerHQ/ledger-app-otherdime

**Comment by sleepdefic1t** [comment]
After some time researching this... I keep coming back to the fact that we’d need to implement quite a few things to even do this meaningfully, and the majority of the work would be client-side & involve custom schemes.

Attestation is already supported on every Ledger out-of-the-box.. and at the end of the day, Ledger will always deser & display whatever it was sent unless it was compromised.. and if a device or app are compromised, there are still ways they can just lie.

There seems to be no clear benefit without entirely new features/schemes to make it all worth it, and nothing we’re currently doing that would interfere with other forks adding attestation schemes if they wanted to.

**Comment by fix** [comment]
Agree low priority in the end, since the surface attack is very narrow. However keep in mind that the key SHOULD be also used with ledger live (that would perform the integrity check) to completely remove the risks

**Comment by sleepdefic1t** [comment]
@fix That all assumes nothing is compromised.. and we’re not actually guaranteeing anything since our cert isn’t factory-installed.

Where I see this being something useful is if a user already trusts their environment/Ledger _then_ enrolls a custom cert tied to a user-provided identity... maybe even creating a unique wallet that can’t be faked.

Otherwise, there’s nothing we can reasonably do to stop a malicious client from just lying.
