### ISSUE TITLE
Architectural Flaws & Performance Issues

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/desktop-wallet#1709]
# Introduction

The Desktop Wallet has been facing performance issues again and again since its inception and with the introduction of profiles and plugins, this problem has been exacerbated even though the amount of data that is handled is rather small and does not justify processing times of 1+ seconds for simple tasks that don't require calls to external services.

This issue will be used to explain why some of those issues exist, potential solutions and how to avoid those architectural flaws that result in performance and maintenance problems when new features are implemented or existing ones reworked.

## Electron

Electron itself has a [Performance Guide](https://www.electronjs.org/docs/tutorial/performance) which explains a few of the common mistakes developers make when going from web applications or node.js applications and a few of them apply to the desktop wallet but the main one is [Loading and running code too soon](https://www.electronjs.org/docs/tutorial/performance#2-loading-and-running-code-too-soon) which is one of the main culprits of the bad performance.

## Example

We'll use [client.js](https://github.com/ArkEcosystem/desktop-wallet/blob/develop/src/renderer/services/client.js) as an example throughout this issue as it has multiple flaws in its architecture and usage that are prevalent throughout the application.

**Comment by faustbrian** [comment]
# Classes & Components do too much

> We will just look into one of the worst offenders but more will be looked at in the future.

A theme you'll notice when browsing through the source of the wallet is that classes and components are relatively large with a lot of different tasks they perform. Most of them have full knowledge of every tine step that is involved in a task rather than having all of it abstracted for easier testing, development, maintenance and if all things fail, debugging.

It's a lot easier to reason about small pieces of code rather than monolithic entities. Monolithic entities can be fine (to a certain degree) in the context of a service locator pattern or large classes that serve as a proxy to a lot of underlying classes that shouldn't be directly exposed but in general they should be avoided to reduce the number of potential defects and time to implement new features. The smaller the class or component, the more efficient you'll be with applying TDD and ultimately reduce the time of implementation without defects.

A common solution to this usually is the use of [Composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance) which is already applied to components **(UI wise)** but not to functional code like services. Another issue that goes hand in hand with this is the violation of the [Single responsibility principle](https://en.wikipedia.org/wiki/Single_responsibility_principle) in a majority of the services and various randomly placed classes.

Let us have a look at the [client.js](https://github.com/ArkEcosystem/desktop-wallet/blob/develop/src/renderer/services/client.js) that was mentioned earlier and break down why its design is bad and what the resulting performance implications are in how it is constructed and used.

## Too many responsibilities

The first thing you'll notice when opening the file and glancing over it is that it does a whole lot of things that don't exactly match what a `client` traditionally does. There could be a better name for it but I can't come up with one quickly which indicates there is too much going on to assign a single descriptive name to it.

As a start, it is responsible for holding an instance of the Client that is exposed by the `@arkecosystem/client` package. This in itself is fine and matches the class name of a client, we simply provide an abstraction that hides some of the boilerplate and reduces duplication across the application.

Next up you'll encounter functions that perform calls to the `@arkecosystem/crypto` package which is odd, didn't this class say it is strictly a client? Even further down you'll encounter a function called `__watchProfile` which interacts with the [vuex](https://vuex.vuejs.org/) storage, again completely unrelated to what the name of the class would indicate.

You might've guessed by now what the problem is. **We are doing too many things for too many domains.** The client should strictly be used for communication with the network. It has no need or justification for its knowledge of the cryptography that is involved or that there is a storage that holds some data that comes from itself.

All it needs to know to do its job is to get a certain input, send it to the network and return the output but how that input was created or what happens with the input is none of its concerns. This will lead us to the next point which as a side-effect causes performance issues during the application bootstrapping.

## Large number of imports

Now that we know that the `client` is trying to do too many things you'll notice that there is a large number of imports right at the top. This violates what is recommended in [Carelessly including modules](https://www.electronjs.org/docs/tutorial/performance#1-carelessly-including-modules) and [Loading and running code too soon](https://www.electronjs.org/docs/tutorial/performance#2-loading-and-running-code-too-soon) for a few reasons but causes even more harm in our case.

```ts
import { Connection } from '@arkecosystem/client'
import { Identities, Transactions } from '@arkecosystem/crypto'
import * as MagistrateCrypto from '@arkecosystem/core-magistrate-crypto'
import { castArray, chunk, cloneDeep, orderBy } from 'lodash'
import moment from 'moment'
import logger from 'electron-log'
import { TRANSACTION_GROUPS, TRANSACTION_TYPES } from '@config'
import store from '@/store'
import eventBus from '@/plugins/event-bus'
import BigNumber from '@/plugins/bignumber'
import TransactionService from '@/services/transaction'
import WalletService from '@/services/wallet'
import priceApi from '@/services/price-api'

Transactions.TransactionRegistry.registerTransactionType(MagistrateCrypto.Transactions.BusinessRegistrationTransaction)
Transactions.TransactionRegistry.registerTransactionType(MagistrateCrypto.Transactions.BusinessResignationTransaction)
Transactions.TransactionRegistry.registerTransactionType(MagistrateCrypto.Transactions.BusinessUpdateTransaction)
Transactions.TransactionRegistry.registerTransactionType(MagistrateCrypto.Transactions.BridgechainRegistrationTransaction)
Transactions.TransactionRegistry.registerTransactionType(MagistrateCrypto.Transactions.BridgechainResignationTransaction)
Transactions.TransactionRegistry.registerTransactionType(MagistrateCrypto.Transactions.BridgechainUpdateTransaction)
```

The first thing you'll notice is that we import `@arkecosystem/crypto` and `@arkecosystem/core-magistrate-crypto` which are related to cryptography, which we deemed as unfit to be of concern for a client. There are also `@/services/transaction` and `@/services/wallet` which also export those packages.

On first glance, this might seem harmless and you're asking yourself what the problem with it is since that is how you require modules in your node.js applications but requiring modules in Electron applications is more expensive because you don't know what hardware a user runs and you won't be able to change that. When you run your node.js application on a server you are in control and can just upgrade your server if the application is sluggish but an Electron application runs on your user's system and requires you to write the most performant code you can produce.

## Too early inclusion of cryptography

The first problem with those includes is that none of them are of immediate use after the construction of the class but they will be bootstrapped which will eat up a signification portion of the booting time due to the cryptography having native and large dependencies which take time to bootstrap. We are only taking a second here but in terms of perceived launch time for a user that is a lot.

This performance issue can be resolved by extracting the cryptography related imports and calling them through a `getter` to not load them before they are actually needed.

**client.js**
```ts
get TransactionService () {
	return require('@/services/transaction').default
}

get WalletService () {
	return require('@/services/wallet').default
}
```

**crypto.js**
```ts
import { Identities, Transactions } from '@arkecosystem/crypto'
import * as MagistrateCrypto from '@arkecosystem/core-magistrate-crypto'

Transactions.TransactionRegistry.registerTransactionType(MagistrateCrypto.Transactions.BusinessRegistrationTransaction)
Transactions.TransactionRegistry.registerTransactionType(MagistrateCrypto.Transactions.BusinessResignationTransaction)
Transactions.TransactionRegistry.registerTransactionType(MagistrateCrypto.Transactions.BusinessUpdateTransaction)
Transactions.TransactionRegistry.registerTransactionType(MagistrateCrypto.Transactions.BridgechainRegistrationTransaction)
Transactions.TransactionRegistry.registerTransactionType(MagistrateCrypto.Transactions.BridgechainResignationTransaction)
Transactions.TransactionRegistry.registerTransactionType(MagistrateCrypto.Transactions.BridgechainUpdateTransaction)

export { Identities, Transactions, MagistrateCrypto }
```

This small refactor will save roughly a second of the application bootstrap time which is almost 33% of the time on a stock installation with 1 wallet. This should be further optimized by moving it completely into the background or a thread, maybe even make use of preloading.

## Too early inclusion of store

The second issue is the `@/store` import. For a yet unknown reason, the bootstrapping of it with the default database and 1 empty wallet takes a total of 1.0 to 1.5 seconds. This in itself is odd but why would the supposed client have to even know about the store or at least that early in the lifecycle? The bootstrapping of the store is the second most expensive action after the loading of the cryptography dependencies with the key difference that it gets exponentially worse as the size of a profile keeps growing.

We can apply the same solution as we did for the cryptography of using a `getter` and thus turning the `@/store` into a dynamic requirement.

```ts
get store () {
    return require('@/store').default
}
```

But as you'll notice when applying this change it's not helping us as this will lead us to another issue in the client. When the client is constructed it calls the `__watchProfile` method which in turn triggers the requirement of the `@/store` which takes roughly a second.

```ts
constructor (watchProfile = true) {
  this.__host = null
  this.client = new Connection('http://localhost')

  if (watchProfile) {
    this.__watchProfile()
  }
}
```

The coupling of the client to other services is currently so tight that it is difficult to solve the resulting performance issues in a reasonable manner like using service workers or reorganizing the application lifecycle during bootstrapping. Also, without resolving the `store` performance issues the other potential tweaks won't have much of an impact as their execution times are almost static **(almost entirely tied to the user's hardware)** and won't grow exponentially with more data being added to the wallet.

> When looking at the performance of the `store` the best spot to start digging is `RESTORE_MUTATION` as disabling it **(for obvious reasons)** resolves the long execution time of the store construction.

**Comment by faustbrian** [comment]
# Vuex Persistence

The [Vuex](https://vuex.vuejs.org/) storage is currently persisted through [vuex-persist]|(https://github.com/championswimmer/vuex-persist) which is a plugin that supports storage adapters. We use [localForage](https://github.com/localForage/localForage) as an adapter but it has known performance issues, see https://github.com/localForage/localForage/issues/315 and https://github.com/localForage/localForage/pull/656.

The `localForage` performance issues are less of an issue than the `vuex-persist` performance issues which already cause several 100ms delays just with a few dozen keys. The way `vuex-persist` stores the data when calling `RESTORE_MUTATION` is that it loops over every single key in the object and assigns its value to `this._vm.$data` through the `this._vm.$set` method.

This way of storing the data can be rather slow then simply dumping all of the restore data into the VM with `Object.assign(this._vm.$data.$$state, merge(state, savedState || {}))`. Ideally, we could even drop the `merge` because we restore the vuex data very early on so nothing else has yet touched the store. For our use-case there is no need to merge, check if something already exists or do partial assignments, we just need to dump the whole data into the VM.

> Using the `Object.assign` approach saved roughly 150-200ms during the start and this could be further optimized by cutting out some for us useless code from vuex-persist.

**Comment by davimello28** [comment]
I'm happy to see this. This is one of my goals on https://github.com/ArkEcosystem/desktop-wallet/issues/1676 and this is why is taking more time. 

Some more pratical points that I would like to add.

- Using more submodules and multi-file components and improve strategies for creating/validating an instance of a class. This cooperates with almost every point you made.  
- Better error handling and logs for debugging. This can be achieved by creating multiple error classes and creating a proper hierarchy for errors. 
- Define the relationship between elements that come from the UX and from the UI. Allowing modals and dialogs to stack for example.

**Comment by faustbrian** [comment]
Closing, no longer relevant for 3.0
