### ISSUE TITLE
bug: dropdown menu misaligned with parent button

### ISSUE THREAD

**Issue by brenopolanski** [ArkEcosystem/desktop-wallet#1852]
**Current Behavior**

![Peek 2020-03-16 17-18](https://user-images.githubusercontent.com/1894191/76996869-0c5da880-6931-11ea-8173-dca8b17d48df.gif)

![Screenshot from 2020-03-16 17-17-08](https://user-images.githubusercontent.com/1894191/76996925-25665980-6931-11ea-8273-2194e8d5f009.png)
![Screenshot from 2020-03-16 17-16-52](https://user-images.githubusercontent.com/1894191/76996927-26978680-6931-11ea-97a0-10cde646fe78.png)
![Screenshot from 2020-03-16 17-16-39](https://user-images.githubusercontent.com/1894191/76996929-26978680-6931-11ea-806a-391f02285634.png)

**Your Environment**

- Version used: `develop`
- Environment name and version: Chrome v80.0.3987.86 - Node.js v12.13.0
- Operating System and version: Ubuntu 19.10

**Comment by faustbrian** [comment]
Closing, no longer relevant for 3.0
