### ISSUE TITLE
Delegate rank does not update on DEVNET Main Screen

### ISSUE THREAD

**Issue by blib423** [ArkEcosystem/desktop-wallet#192]
The delegate rank does not update on the main screen on DEVNET network.  It does update correctly on the individual accounts page under the "votes" tab, but not under the "delegate" tab nor on the main screen. This is true even after refreshing or restarting the client.

**Comment by RoundQube** [comment]
Anyone working on this issue?  I'd like to tackle it.

**Comment by darfraider** [comment]
Anyone working on this?  I'd like to work on it.

**Comment by j-a-m-l** [comment]
@darfraider if this bug persists, and, as you said, you'd like to work on it, please do it ;)
