### ISSUE TITLE
Wallet Tab with Links to How to Documents 

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/desktop-wallet#208]
Hi 

I was thinking about ease of use, would it be possible to have a link/tab/ button on the wallet pointing to how to guides or instructional videos if there are any. Anyone downloading for the first time may have questions on how to use. This would make the general new users experience easier.

Someone like dr10 could create some short 1 min vids which are either linked to the wallet or something like that..

Thanks

Jamie

**Comment by SBero** [comment]
Maybe something like this?

https://youtu.be/CgD4WqHJFtU?t=219

**Comment by jamiec79** [comment]
Yep, or just a link to short 1 min vid's covering in wallet demo of how to vote/unvote... or how to setup 2nd phrase or how to send and receive a txn..
