### ISSUE TITLE
Ark Wallet Account Bug

### ISSUE THREAD

**Issue by Brodinson** [ArkEcosystem/desktop-wallet#210]
I'll just paste the post that i made on reddit as i am now confinced it must have been a bug.

So i just downloaded the ARK client and installed it as i was planning to send my ARK over from bittrex so that i could vote for a delegate.
After i downloaded and installed the client i got my original passphrase and i write that down go to the next step and it asks for 3 of the 12 words and i fill that in and all is well.
I'm liking the looks of the client up until this point and after i finished their check to see if my passphrase was written down correctly i get a screen with my account and my adres.
So trying to be safe i immediatly check the security options and find a 2nd passphrase option so i click on that only to get told i need at least 5 ARK in my wallet to be able to set a 2nd passphrase.
I'm thinking that that makes sense so i login to my bittrex to withdraw my ARK and continue to send it to the adres in my account. The transaction went very fast and it was in my wallet in no time so im happy and all is well.
Back to setting that second passphrase i thought and now it let me since i had more than 5 ARK. It gives me the second passphrase to write down and i click next. Now it asks me my original passphrase and the second passphrase so i fill those in... it then tells me that the passphrase does not fit those of the account.
I stay calm thinking i must have made a typo in my first and/or second passphrase so i try again but no cigar. At this point i'm starting to worry.. did i maybe write my passphrase down incorrectly??? I look at my piece of paper and count the number of words, there are 12, no problems there. Then i check if maybe some words could be something else like maybe i wrote down ''dad'' instead of ''dead'' but after trying a few things this doesn't work either.
At this point i'm convinced that my passphrase must be correct and that it must be something with the account so i try the ''import account'' option and fill in the original passphrase that i wrote down and bingo a second adres shows up.. the supposed original.
So now I'm sad and pissed at the time as i now have an open client with 2 adresses with money in the one i don't have acces to.
I don't know how this happened..
Why did the client show a wrong account after the initial startup? And why does there need to be at least 5 ARK in your account when setting up a second passphrase? Because without that restriction i would have found out that i had an account without the correct passphrase before i sent my ARK over.
The only upside to this story is that i only had 40 ARK so my losses aren't that big but as someone who has just recently started trading cryptocurrency and as someone who decided to start off with an initial investment of only $200 it really really sucks.
This was the (wrong) adres my coins went to: AaPLz4aWCFcRQcqE1khSLnckXiiAcoraCw
And this was where it was supposed to have gone: Aem4E2s8h4ytq6uiEmJnj466uPahsu8oMt
So yeah i guess the moral of the story is always triple check and that when you first start with the ARK client that you want to first remove the account that it starts with and then import one using the passphrase that you wrote down. This way you know nothing can go wrong.
I hope that this helps others that decide to use the ARK client to not lose their money to an inaccesible wallet.
Sorry for the wall of text everyone :P.
Edit: This is what it now looks like: http://i.imgur.com/zVR5FbU.png just sitting there looking at me. Also i know it isn't supposed to be safe to make a screenshot of your client but i really couldn't care less in this case.
Edit 2: Edit: Also i just checked if it could have been a user error by me by clicking create a new account. But this confirms that it could not have been my own mistake as creating a new account asks you to write down a new passphrase and then afterwards asks you to write down words nr3 nr 6 and nr9 of that passphrase.. so it's not like i could have deleted my original account and then made a new one without writing down the new passphrase that comes with it unless i somehow remembered words 3, 6 and 9 by just glimpsing at a passphrase for a split second before clicking next.
I really hope a developer or mod reads this because this confirmed for me that it wasn't a user error made by me. I made no mistakes.

**Comment by luciorubeens** [comment]
Hi @Brodinson, try to transfer in the Lite Wallet: https://arkecosystem.github.io/ark-lite-wallet/app

**Comment by boldninja** [comment]
@Brodinson look at 12 words again and if you added space or anything at the beginning or end - each char change will result in different Ark address being imported. Make sure when you are importing you are importing it in exactly like it was shown to you. Note that same passphrase will always open same Ark address (try for instance importing this 12 words I used to create new Ark address without ):

exact sleep bargain shock choose exercise pledge public tribe express broccoli attack

Results in importing Ark address = Ac5SmeBon8azcUQv6q8uqYa24eMMuLCY9w, no matter in which wallet you'll try.

**Comment by Brodinson** [comment]
I don't think that would work either as a transfer requires the passphrase
aswell.

Op 17 aug. 2017 4:54 a.m. schreef "Lúcio Rubens" <notifications@github.com>:

Hi @Brodinson <https://github.com/brodinson>, try to transfer in the Lite
Wallet: https://arkecosystem.github.io/ark-lite-wallet/app

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ArkEcosystem/ark-desktop/issues/210#issuecomment-322955196>,
or mute the thread

**Comment by fix** [comment]
@Brodinson reading your text, first thing poping up in my mind: Is it possible you mixed passphrase and the second passphrase when you tried to register it (and failed)?

**Comment by zillionn** [comment]
I believe he means that he wrote wrong the 1st pass but he found out about that only after he moved his ARK out of Bittrex because he needed them to register the 2nd pass.

Create a text file with different passphrase combinations. Maybe you wrote some word(s) wrong. Check the spelling.
Remove your account and try importing it by copy paste those different passphrases.

**Comment by MLVDB** [comment]
Damn!! I had the exact same problem. This must have happened to a lot of people by now.
So no answers Brodinson? I just send a mail to them but not expecting much! just as i wa starting to enjoy the marketing...;(

**Comment by zillionn** [comment]
It's up to you guys to save your passphrases correctly, it's nobody else's.

Tip: Every time you create a new account, save the passphrase and the address, immediately delete the account and import it with the passphrase. Compare the saved address with the one imported to be sure you have the right passphrase. If you import different address, then the passphrase is wrong.

**Comment by sleepdefic1t** [comment]
#
> [r/ArkEcosystem/just_a_heads_up_regarding_the_ark_client/](https://www.reddit.com/r/ArkEcosystem/comments/6u3xtz/just_a_heads_up_regarding_the_ark_client/)
>
> RESOLVED: See bottom of the post.
>
> Edit 3: I sent my passphrase Jarunik and he found the problem real quick. It was a user error afterall.. there was a word that is 99.9% the same in English and in Dutch but the english variant has an extra letter at the end and this is where i went wrong as my brain must have filled in the Dutch variant.
>
> I thought it must have been a bug because when i imported an account with the incorrect passphrase it provided me with an adres of which i thought was the correct one but that's just how the system works.
>
> So in the end i feel like a bit of a dumbass but at the same time it's a good ending for me so a big shoutout to Jarunik for helping me out. You are awesome.

![close](https://media.giphy.com/media/ghGnhdda9Ru4E/giphy.gif)
