### ISSUE TITLE
Save Passphrase (up for discussion)

### ISSUE THREAD

**Issue by boldninja** [ArkEcosystem/desktop-wallet#228]
Since a lot of people still don't save their passphrases or seem to not write it correctly should we add a button in lower left corner something like this or not so wise (security wise of course)?

![createaccounty](https://user-images.githubusercontent.com/25795454/29948554-c1e7baec-8eaf-11e7-862d-dba9d442532f.png)

**Comment by fileninja** [comment]
One way Would be to Let the User Print the passphrase as a Document.

**Comment by zillionn** [comment]
And maybe add another line of text:
!!! IF YOU LOSE YOUR PASSPHRASE, ALL YOUR FUNDS IN THIS ACCOUNT WILL BE LOST !!!

**Comment by boldninja** [comment]
@zillionn I agree, people are still thinking too much passphrase can be recovered and thinking of old ways. We need to remind them on every step that if you don't save it or save the wrong one your funds are lost forever and there is nothing anyone can do about it.

**Comment by zillionn** [comment]
And the background should be red like all warning messages.

**Comment by fix** [comment]
this is linked to BIP38 integration proposal. We should propose the
capabilities to export encrypted wallet for that purpose instead

Fix

**Comment by DooblyNoobly** [comment]
Hi, as a first time user (today) of the wallet I would like to say that asking for the separate words (word 3, word 9 etc) is a really effective way to ensure the user has recorded the passphrase. I do not think you need to go any further then this. Or if you do then maybe just a warning in red under that part of the ux
