### ISSUE TITLE
Error in translation

### ISSUE THREAD

**Issue by Bluffet** [ArkEcosystem/desktop-wallet#233]
The Norwegian translation should read Norsk, not Nynorsk. 

To clarify: Both Norsk and Nynorsk are official languages. Nynorsk just counts for around 5-10% so it makes no sense to support it. They are not much different anyway.

**Comment by ckhatri** [comment]
Hi, sorry where do you see this? I don't see Norwegian as an option in the wallet. Settings -> Language -> ?

I've looked at the code as well and don't see Nynorsk anywhere.

**Comment by Bluffet** [comment]
![screenshot 2017-09-06 01 35 40](https://user-images.githubusercontent.com/31476976/30087941-e191aa0e-92a3-11e7-89f2-21de1a32582b.jpg)

Link to translation: http://osjc1wl.oneskyapp.com/collaboration/translate/project/project/95031/language/15#/page/2

It should read "Norsk", it benefits more and is the written language for roughly 90% of the population.

**Comment by Bluffet** [comment]
See it clearer now? It is the category at the top. I am unable to change it. Probably because of privileges. Once fixed, it could be production ready.

**Comment by ckhatri** [comment]
Ah yes! Sorry, I thought this issue had to do with the desktop application. I also have no privileges there. 

Thanks for the clarification!
