### ISSUE TITLE
Freezing Application with Ledger Signing

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/desktop-wallet#241]
The Ledger and desktop application freezes when trying to sign a transaciton.

Reproduction:
1) Create a transaction and send 1 Ark to an Address
2) Sign with ledger
3) Wait a bit and then hit ok on ledger
4) Cancel transaction
5) Redo from 1) ... usually after 2-3 tries it freezes

Then you have to unplug ledger and reload wallet.

**Comment by fix** [comment]
Yes i am not completely happy about it but there is one dificult thing: "node-hid" used to communicate with ledger is running inside the electron process (and not the client process), which means freeze the whole application while waiting the response from ledger...

Does the ledger freeze as well? in that case might be the app on ledger having issue with clearing memory.

**Comment by boldninja** [comment]
Maybe when it waits for response from ledger some popup window popsup - confirm your TX on ledger or something so even when frozen you see it until you confirm on Ledger?

**Comment by Jarunik** [comment]
I think the ledger freezes as well. You can't do anything on it.

**Comment by timart1n** [comment]
Tried to reproduce it but was not able to.
Neither the ARK Desktop nor the ledger freezed. Found only what I described here #319 .

Tried only on Windows 10 Build 15063.608.
Ledger Firmware 1.3.1.

**Comment by boldninja** [comment]
This will be fixed in new release @timart1n 

https://github.com/ArkEcosystem/ark-desktop/pull/267
