### ISSUE TITLE
Images not showing up in desktop client

### ISSUE THREAD

**Issue by miloops** [ArkEcosystem/desktop-wallet#261]
Images are not being loaded in ark desktop. I'm on Arch Linux, I had this issue both downloading desktop client and building from source: clone, npm install, npm, start.

![screenshot from 2017-09-13 10-57-25](https://user-images.githubusercontent.com/3359/30381375-c5fe33d2-988b-11e7-9ff4-6e89b4f73be2.png)

**Comment by SBero** [comment]
Seeing that you've got a Ledger Nano S, I've had nothing but issues around node-hid. Did you get any kind of errors when npm install was rebuilding?

**Comment by miloops** [comment]
@SBero looks like I do get some issues on node-hid:

`> node-hid@0.5.4 install /home/miloops/media/blockchain/ark-desktop/node_modules/node-hid
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/bin/node',
node-pre-gyp verb cli   '/home/miloops/media/blockchain/ark-desktop/node_modules/node-hid/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.31
node-pre-gyp info using node@8.4.0 | linux | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/home/miloops/media/blockchain/ark-desktop/node_modules/node-hid/build/Release/HID.node" (not found)
node-pre-gyp http GET https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v57-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v57-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-hid@0.5.4 and node@8.4.0 (node-v57 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v57-linux-x64.tar.gz 
node-pre-gyp verb command build [ 'rebuild' ]
make: Entering directory '/home/miloops/media/blockchain/ark-desktop/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o
../hidapi/libusb/hid.c: In function ‘hid_read_timeout’:
../hidapi/libusb/hid.c:1078:6: warning: variable ‘bytes_read’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
  int bytes_read = -1;
      ^~~~~~~~~~
  AR(target) Release/obj.target/hidapi.a
  COPY Release/hidapi.a
  CXX(target) Release/obj.target/HID/src/HID.o
../src/HID.cc:69:5: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     throw(JSException);
     ^~~~~
Emilio • Now
`

**Comment by SBero** [comment]
Going off of memory to solve this and it was on osx, but I'd try wiping out the node_modulea directory and using yarn to install the packages instead of npm, once I did that, I did another npm install (should run a number or commands if you look in the package.json file) and everything worked for me. Let me know if that works.

Otherwise I'd need to setup a copy of Arch and check it out. Don't have a ledger s to check against however.

**Comment by miloops** [comment]
I don't think ledger has anything to do, I'm having the same issue with or without it. And also downloading linux compiled version or running npm myself... 

I'm getting this error now:

```
An unhandled error occurred inside electron-rebuild
ENOENT: no such file or directory, open '/home/miloops/media/blockchain/ark-desktop/node_modules/node-pre-gyp/package.json'

Error: ENOENT: no such file or directory, open '/home/miloops/media/blockchain/ark-desktop/node_modules/node-pre-gyp/package.json'
```

**Comment by SBero** [comment]
Correct. I don't think ledger itself has any direct issue creating it, but the node-hid package which is needed to interface with it, I think is creating issues.

Did you delete the node_modules first before running yarn install?

If that doesn't work, I'd see about trying a manual npm install of the issue package to see it resolves the issue.

**Comment by miloops** [comment]
Yes, I deleted node_modules before, I was also able to `npm install node-hid`, then ran npm install and looks like the build was successful. Then, `npm start`, client starts... same issue, no images are being loaded.

**Comment by SBero** [comment]
Ok. I'm going to setup Arch Linux to see if I can replicate as well.

Thanks for the screenshots. The errors you're seeing, I see as well on OSX.

**Comment by fix** [comment]
For last screenshot, this is normal. For image loading, maybe some issue for archlinux...

**Comment by miloops** [comment]
Were you able to reproduce @SBero ? I downloaded latest source code and also tried with latest client, but I'm still having the same issue. Let me know if I can do any debugging to help
