### ISSUE TITLE
Issue creating new account

### ISSUE THREAD

**Issue by Superfil** [ArkEcosystem/desktop-wallet#266]
I have downloaded the newest version of the ARK client (1.3.2) and when I try to create an account, after I have received my passphrase, and then confirmed the 3rd, 6th and 9th words of this phrase, I am redirected to the home screen, and no account has been created. What am I doing wrong?

**Comment by j-a-m-l** [comment]
Could you try the latest version, please?

**Comment by alexbarnsley** [comment]
I believe there's a bug which is fixed (may still need to go live) where an account can't be created without connection to a peer (PR #341). That may not be the cause here though, so upgrade as @j-a-m-l suggested and make sure you're connected to the network
