### ISSUE TITLE
Feature Request: Import Ledger passphrase

### ISSUE THREAD

**Issue by digitron-lisk** [ArkEcosystem/desktop-wallet#274]
As it is now, if your Ledger breaks or gets lost, you have no way to access your funds until you get hold of another Ledger. So it would be nice to have the ability to import the Ledger passphrase into the wallet in case of this emergency.

**Comment by peterdouglas** [comment]
I will need to test this, but I think this is already supported - as the passphrase uses the BIP39 passphrase, so it should already support it by default.

**Comment by digitron-lisk** [comment]
I tested it. Created a new wallet with a 12 word passphrase on Ledger and imported the same 12 words into ark wallet. Resulting in 2 different addresses.

**Comment by boldninja** [comment]
Importing Ledger passphrase "normally" via import won't result in the same ARK address as Ledger is also using SLIP44 ( https://github.com/satoshilabs/slips/blob/master/slip-0044.md ). There could be potentially added a feature to import it from Ledger passphrase, but again this should be really used as a last resort (if you really cannot buy new Ledger) as it totally negates the need for hardware wallet if you are importing it normally.

**Comment by digitron-lisk** [comment]
Agreed boldninja, should come with double warnings. But it can be a life saver. Consider the scenario, you all of a sudden need a lot of money for any kind of emergency. You fire up your Ledger only to find it's broken. If that happens now, you are in for a 4 week wait before you can access your ARK again

**Comment by peterdouglas** [comment]
@digitron-lisk thanks for testing that! I was going off the ledger support doc [here](http://support.ledgerwallet.com/knowledge_base/topics/what-happens-if-i-lose-my-ledger-wallet). Apologies I was incorrect.
@boldninja thanks for the correction!

**Comment by fix** [comment]
it is already wired https://github.com/ArkEcosystem/ark-desktop/blob/master/client/app/src/ledger/LedgerService.js#L72

But not yet available in the UI.

If you want to recover so far, you will need to open the development console (ctrl+d) and write:
```
angular.element(document.body).injector().get('ledgerService').recoverBip44Accounts('passphrase')
```

Also if you want to script everything manually, you can get the HD node and recover keys from derivation path doing:

```
var hdnode = new require('arkjs').HDNode.fromSeedHex(require('bip39').mnemonicToSeedHex(backupLedgerPassphrase));
var keys = hdnode.derivePath(derivationPath).keyPair;
```

**Comment by alexbarnsley** [comment]
@fix Could a potential route to import ledger account(s) be to require the funds get transferred to another address?

**Comment by alexbarnsley** [comment]
@fix i tried your first piece of code but that just gave me read-only data. Are we talking about read-only or full-on access to a ledger wallet with the master passphrase only?
