### ISSUE TITLE
Ledger Nano S Invalid status 6d00

### ISSUE THREAD

**Issue by MaxKotlan** [ArkEcosystem/desktop-wallet#277]
I can't sign messages with the Nano S. For some reason I'm getting this 6d00 error message when I try.

**Comment by fix** [comment]
Yes, signing messages is not yet supported. Maybe we should disable this tab if the address is from ledger, to prevent from frustration @luciorubeens

**Comment by alexbarnsley** [comment]
@fix what is stopping us implementing signing of messages with a ledger? I could take a look.

**Comment by fix** [comment]
needs to be implemented on the ledger app https://github.com/ArkEcosystem/ark-ledger

**Comment by alexbarnsley** [comment]
@fix I didn't know that existed! I thought ledger themselves created the app 👀

**Comment by boldninja** [comment]
@alexbarnsley Fix did most if not all of it.

**Comment by alexbarnsley** [comment]
@boldninja I'm not surprised! I can see from the commits. Just felt like a closed source app on the ledger. @fix is just full of surprises!

**Comment by fix** [comment]
yes i wrote the app, but ledger reviewed it, and the signature was all bad cooked, so i decided to remove it for this release.
