### ISSUE TITLE
I try send transaction with Ledger, but not could sign. version 2 not supported

### ISSUE THREAD

**Issue by joonahenrik** [ArkEcosystem/desktop-wallet#3174]
**Expected Behavior**

**Current Behavior**

**Possible Solution**

**Steps to Reproduce (for bugs)**

**Context**

**Your Environment**

- Version used:
- Environment name and version (e.g. node.js v10.15.3):
- Server type and version:
- Operating System and version:
- Link to your project:

**Comment by sleepdefic1t** [comment]
@joonahenrik That is typically related to being stuck on a bad peer. Try refreshing your peer connection or entering a peer manually.

**Comment by joonahenrik** [comment]
ThanksLähetetty laitteesta Galaxy
-------- Alkuperäinen viesti --------Lähettäjä: Simon <notifications@github.com> Päivämäärä: 4.1.2021  0.22  (GMT+01:00) Saaja: ArkEcosystem/desktop-wallet <desktop-wallet@noreply.github.com> Kopio: joonahenrik <joonahenrik2.0@gmail.com>, Mention <mention@noreply.github.com> Aihe: Re: [ArkEcosystem/desktop-wallet] I try send transaction with Ledger, but not could sign. version 2 not supported (#3174) 
@joonahenrik That is typically related to being stuck on a bad peer. Try refreshing your peer connection or entering a peer manually.

**Comment by sleepdefic1t** [comment]
@joonahenrik Closing this out if your issue is resolved. Feel free to leave additional comments if you need further support, or join us on the [ARK Ecosystem Discord](https://discord.ark.io/).
