### ISSUE TITLE
Show progressbar while waiting for ledger signature

### ISSUE THREAD

**Issue by timart1n** [ArkEcosystem/desktop-wallet#319]
So basically when the user whishes to sign with the ledger I noticed that between we click sign with ledger from the ARK client and untill we actually sign in the device the UI is seems to go back to the main windows (the modal closes) but in fact its frozen untill an answer arrives.

If the user actually does some actions they are then performed once the window unfreezes.

A simple solution is to providea modar with a progress bar/circle and a message like waiting for ledger signature.

What do you guys think? In the beginning it happened to me that I was just looking at the screen waiting for some input of the next step of the flow and actually my ledger was already prompting me for signing confirmation.

**Comment by timart1n** [comment]
By the way Im new to the whole nodejs/electron/angular environment but would like to contribute a bit to the project and get some basics on the environment so if you guys want to see this in the app I can try and make this small change. Would be good starting point.

**Comment by fix** [comment]
that is a bit tricky because so far the ledger signature is done on main.js thread so effectively freezing the interface until the ledger answers.

What can be done is:
- before sending signature to ledger, add an overlay on the client mentioning the user should watch and interact with ledger
- when signature is done, remove that overlay and process with sending tx.

One improved implementation: move all communication with ledger to the forked process (https://github.com/ArkEcosystem/ark-desktop/blob/master/ledger-worker.js) and handle communication so client does not freeze (however i think the freeze is nice preventing user from doing wrong thing)

**Comment by timart1n** [comment]
I noticed, I was planning on passing the ledger logic to the background with electron-remote taskpool, while still blocking the user input with a modal launched with  mdDialog directive having the main window as parent.

This will make the GUI responsive as the modal will have an indeterminate spinner saying waiting for ledger signature while still preventing the user from harmfully interactions.

I'll post a print withy current implementation when her home tonight.

**Comment by timart1n** [comment]
So [this](https://www.dropbox.com/s/7e3qaas1196jchm/prototype.gif?dl=0) is what I meant.
Today Ill check if I can put the ledger logic on the background.

**Comment by timart1n** [comment]
So after some time today looking into this, I think I can make every ledger related request asynchronous.
This should help with the responsiveness as it will free the main and renderer threads, as soon as I have something concrete ill make a pull request ;)

**Comment by fix** [comment]
nice, i would even make a full screen overlay with a nice picture made by oleg so people understand they have to deal with ledger @boldninja

**Comment by boldninja** [comment]
@fix ok

**Comment by timart1n** [comment]
Ok, this we can discuss once I create the pull request.

**Comment by boldninja** [comment]
@timart1n https://ark.io/loading-nano.png   and you can in that circle get electron loading gif or something and underneath text with translate tag. Like "Look at your Ledger device. Waiting for your  confirmation on Ledger." ?

**Comment by fix** [comment]
can we get some transparent instead of white on the outside?

**Comment by boldninja** [comment]
https://ark.io/FixIsBoss.png

**Comment by timart1n** [comment]
Hey guys.
Still WIP, but would like some feedback if you have the time ;)
#324
