### ISSUE TITLE
Feature request: Allow to unvote and vote in one transaction

### ISSUE THREAD

**Issue by biolypl** [ArkEcosystem/desktop-wallet#346]
This could save user 1ARK per voting transaction. I'm not sure if it is possible with current ARK-js but if yes, it will be great get implemented in ARK Desktop
![screenshot at 13-21-14](https://user-images.githubusercontent.com/19519175/31575285-5245fe1e-b0e3-11e7-9a47-243baf91bb4f.png)

**Comment by alexbarnsley** [comment]
This is already part of the AIP-11 so is coming very soon. That being said, the UI will need updating to cater for it.

I did do a PR to allow for unvote and vote in same process, but not been merged and probably not necessary with the upcoming change (#286)

@fix has work gone into all areas for single re-vote transaction? Or is it worth leaving this open to remember to make the UI change?
