### ISSUE TITLE
Client is not opening up on my surface pro 2017

### ISSUE THREAD

**Issue by 0toierance** [ArkEcosystem/desktop-wallet#384]
Application used to work but all of a sudden just would not open. According to task manager the application is running, without issues. But no icon pops up on my dash.

**Comment by alexbarnsley** [comment]
@0toierance if you kill the process or restart, does it work then? Failing that, a reinstall if that's possible? Strange how it's just happened on its own. Sounds like you haven't updated the client recently?

**Comment by 0toierance** [comment]
I actually update my client as it comes out, I don't procrastinate on that part. I feel it may stem from my recent Windows 10 update.

**Comment by j-a-m-l** [comment]
@0toierance could you give us additional feedback? have you tried to re-install it?

**Comment by bugpwdrdst** [comment]
I have the same problem. 

I have exceptions on my firewall and AV. I tried uninstall and reinstall the newest version. I also tried installing the previous version, although both versions have worked in the past but one day it stopped working and like mentioned before same issue as OP. I can't access the light version with my ledger so have to work with desktop client.
