### ISSUE TITLE
Idea's upcoming wallet release?

### ISSUE THREAD

**Issue by mycameratravels** [ArkEcosystem/desktop-wallet#417]
I love the option to put in your own background image. Great job!
Would it be possible to create a slideshow of background images if you point it to a directory with images?

And to make some images stand out better, it would be great if we could adjust the opacity of the information boxes.

Best regards,
M.

**Comment by fluorine** [comment]
I don't think that feature would be a priority, but I do believe that the user should have more control on the style of the wallet, which would be great and I think is easy to implement.
