### ISSUE TITLE
Intermittent Overlap issue

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/desktop-wallet#423]
![image](https://user-images.githubusercontent.com/8069294/33046996-679cf940-ce4b-11e7-8e02-d5a4e09a2166.png)

All tabs seem to overlap each other on first launch. It doesn't always happen. The temporary fix is to click on each tab (Transactions, Votes, etc) - restarting should also work

**Comment by j-a-m-l** [comment]
Uhmm, @alexbarnsley I can't reproduce it

**Comment by alexbarnsley** [comment]
@j-a-m-l yeh it doesn't happen often. Only happened once for @boldninja (that's his screenshot of devnet above)

Not urgent I don't think, because it's so intermittent (that no one has reported it). It may be a Windows thing too?

**Comment by sleepdefic1t** [comment]
It has a lot to do with the way views and layers are drawn vs your given monitor and resolution.

Play with your resolution and the size of the window and you should be able to reproduce overlapping elements.

Apple uses Stack Views to make this easier, not sure w/Electron.
AFAIK, it SHOULD be recalculable to limit the given frames' width/height to X% >= frame-content. 

It's such a small bug,
it's probably just more worth considering for future UI redesigns.

We have one of the best wallets available,
but that list view style hurts my eyes anyways.

it'd be cool to see something like this on mobile and desktop.
![pretty list view](https://i.pinimg.com/originals/a0/0f/6b/a00f6bcfee5f5bea2a50ec70c3149918.gif)

**Comment by DukeCounter** [comment]
![arkwallet_gui_glitch2-20171231](https://user-images.githubusercontent.com/33992549/34460993-e21a2966-edec-11e7-9400-7f5cf8d1a70e.png)

as per discussion with @alexbarnsley, I am adding my account for this bug.

- OS: Windows 10
- monitor resolution: 1366 x 768
- client window was maximized

1. It is overlapping of elements but from different tabs. It looks like Transactions, Votes, Sign/Verify Message, Exchange, Offchain tabs are all open at the same time (basically the background is transparent and everything is jumbled on top of each other)
2. Solution was to simply re-launch the client (or Ctrl+R)
'2. a) If I clicked on any of the tabs above, the overlapping went away one by one. After clicking on each tab, the glitch went away even without re-launching.
