### ISSUE TITLE
More comprehensive Passphrase confirmation

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/desktop-wallet#429]
Just a possibility, when you create 1st or 2nd passphrase you should be required to manually write the whole 12 words (no copy and paste), so if you do write it on a piece of paper you will have that copy in front of you. If you then want to copy/paste it you'll have to type it in manually to make sure you have it somewhere at least to write from if you close the client and don't save.

If anyone has any other suggestions, please comment!

**Comment by j-a-m-l** [comment]
I think in a similar manner; it's the best way to avoid typos.

**Comment by Jarunik** [comment]
Please add an option somewhere to disable copy/paste protection to allow it for advanced users.  This 3 words confirmation thing is also super annoying if you need to create 10 wallets.

**Comment by reConNico** [comment]
In my opinion you need to input the whole passphrase to confirm and not only 3 words of it. Also disable copy/paste in this one. 

@Jarunik : You can go with brians creator script when you want to create multiple wallets.
