### ISSUE TITLE
Icons aren't displaying

### ISSUE THREAD

**Issue by n-body** [ArkEcosystem/desktop-wallet#437]
https://i.imgur.com/1LWsLZp.png
https://i.imgur.com/eLC9YQN.png
Using Arch with i3wm, also tried using Cinnamon but still had the same issue.
This occurs with the AUR build as well as the most recent Github release build.
The text overlaps everywhere, making it hard to read anything.
Any ideas?

**Comment by j-a-m-l** [comment]
Weird... I don't have any problems with i3wm. Are those problems on full-screen too?

**Comment by n-body** [comment]
Yes, the problem occurs in fullscreen as well as in other WMs/DEs.  Is there any way I can get a detailed log or something that could potentially help figure out what's causing this?

**Comment by j-a-m-l** [comment]
You can use `Ctrl+d` to open the console.

**Comment by florensie** [comment]
Is the icon font included in the ark-client or is it expected to be installed on your PC?
