### ISSUE TITLE
Voting for Delegates, app stalls after "Sign with Ledger" 

### ISSUE THREAD

**Issue by stechico** [ArkEcosystem/desktop-wallet#440]
* OS X Client 1.4.3 w/ latest Ledger Nano S
* Occurred multiple times

**Comment by Joseph-Tortorelli** [comment]
Weird.  For me, I was able to vote on my ledger.  I am on Windows though so it may be OS X specific.

**Comment by stechico** [comment]
Thanks @Joseph-Tortorelli Let's see if more people may reproduce it on their OS X to confirm.
