### ISSUE TITLE
transactions disappear and ark disappears 

### ISSUE THREAD

**Issue by GeorgeCrev** [ArkEcosystem/desktop-wallet#460]
my ark isnt showing up in my wallet sometimes and sometimes the transactions disappear as well.  then if i restart it shows up.  right when i tried to vote for a delegate it disappeared.  

please help.

**Comment by sleepdefic1t** [comment]
@GeorgeCrev 
Hello, What operating system are you using?

**Comment by GeorgeCrev** [comment]
Windows 7 professional




George Creviston        [magidglove.com]  <magidglove.com>
Regional Vice President of Business Development

MAGID | Safety at work™
1300 Naperville Rd. | Romeoville, IL 60446
773-289-1439
Cell: 815-708-4928 | Fax: 773-289-9439
GeorgeCreviston@magidglove.com
magidglove.com<http://magidglove.com>


[cid:banner_548d4262-9c81-428c-98e8-517df5ea4f7f.jpg]<https://www.magidglove.com/Magid-T-REX-TRX800-Premium-Goatskin-Driver-Style-Impact-Glove.aspx?utm_source=sig&utm_medium=banner&utm_campaign=trx800>
