### ISSUE TITLE
Client window not appearing v1.4.3

### ISSUE THREAD

**Issue by Keithw12** [ArkEcosystem/desktop-wallet#475]
After a fresh install, the client will run.  After I close and reopen the client, the client window no longer appears.  The process is showing in task manager.  I've tried reinstalling and the same issue persists.  It will run once after a fresh install, but any other attempts to reopen fail about 90% of the time.  

Things I've Tried:
Ran installation and client as administrator.
Disabled Windows Defender Real-Time protection.
Reinstalled several times.

Info:
Windows 10 Version 1703 OS Build: 15063.786

**Comment by krl88** [comment]
I have the same issue, although for me it fails to open 100% of the time.

**Comment by geokon72** [comment]
I also have the same issue it fails to open but I can see the aplication is runnning 
in the task manager.I have tried uninstalling + reinstalling the client, restarting my computer and running as administrator but nothing change .
Current version: ArkClient-Win64-1.5.0.exe

**Comment by geokon72** [comment]
Has anyone find a solution?
Version 1.5.1 and it still fails to open.

**Comment by Nasicus** [comment]
Did yo try what I wrote in the linked issue?

**Comment by geokon72** [comment]
If you mean to append the argument --disable-gpu yes I've tried it as I've tried to run in copmpatibility mode.
Also I have another laptop with windows 10 64bit and the ark client works perfectly there.

**Comment by Nasicus** [comment]
I see thanks for the feedback.

Can you try another electron app? 
Let's say take slack: https://slack.com/downloads/windows
