### ISSUE TITLE
Change QR Code to Identicons

### ISSUE THREAD

**Issue by luciorubeens** [ArkEcosystem/desktop-wallet#513]
Hey guys,

One of our goals is to make this wallet user-friendly. Currently, the address is a bit long and difficult to memorize, so if the user has a wallet with more than 3 accounts it will not be practical to identify and select the correct address he wants to view.

My proposal is to change the icons in the wallet list and the QR Code of the current wallet selected to use [Identicons](https://en.wikipedia.org/wiki/Identicon).

> An Identicon is a visual representation of a hash value.

![Github](https://i.imgur.com/uJJj8Jh.png)

So we can use the wallet address to generate the Identicon. But instead of this strange images, we can use something more descriptive, like [RoboHash](https://robohash.org) and [FlatHash](http://flathash.com).

> My username (luciorubeens) in both libraries

<div>
<img src="https://robohash.org/luciorubeens.png" width="80" height="80"></li>
<img src="http://flathash.com/luciorubeens" width="80" height="80">
</div>
<br>
<p>Finally, this is how it will look:</p>
<img width="800" alt="Wallet preview" src="https://user-images.githubusercontent.com/4539235/34801478-c54630b0-f647-11e7-903c-0a247bf7b5fd.png">

And to show the QR Code we could have a button that would open a window.

**Comment by alexbarnsley** [comment]
I love the sound of something a bit more personal. However I'd be more than happy with the first set of icons you sent (https://camo.githubusercontent.com/3421b787d4bdc5731d1b69afc34f1e15770534a9/68747470733a2f2f692e696d6775722e636f6d2f754a4a6a384a682e706e67) - excuse the link, on my mobile. These are a lot like the slack default avatars

I personally think the characters look a bit strange, but that's just me xD

**Comment by Nasicus** [comment]
I find the robots kind of cool and more fitting for Ark than the others. (It also supports the development is a little "further" there at the moment)

But I mean: If we'd want we could probably even make it configurable? (No avatars, the simple ones, set 1, set 2, etc.)

**Comment by j-a-m-l** [comment]
I'd love it. That was one of my undisclosed ideas ;)

About the identicon generator, I prefer the RoboHash because is different from the "normal" style, but I'd accept anything as long as it doesn't produce hash collisions.

**Comment by boldninja** [comment]
I like it as well, but would make it a tab in settings where you can choose QR code, or any of the 3 styles from RoboHash.

**Comment by j-a-m-l** [comment]
I'd use only 1 style because that style could also be used in the explorer and other tools. It's the same coherence that you can see in some Ethereum wallets (MEW, Parity, etc.).

**Comment by zillionn** [comment]
I also very much like the idea. Both libraries are cool, but most adults will probably prefer the FlatHash. Option to choose will be great.

**Comment by vRobM** [comment]
Cartoonish figures preferred. Anything to remove the unsightly QR code which should only be used when needed. (upon click or menu selection)
