### ISSUE TITLE
ARK Desktop App Window Too Large

### ISSUE THREAD

**Issue by vRobM** [ArkEcosystem/desktop-wallet#529]
By default the window is too large. We don't need a full screen wallet app. More like one to use for a transaction, then have it off to the side to monitor activity.

The elements within the window need to look better when the window is resized down.

The resized window size needs to be remembered across app restarts.

**Comment by zillionn** [comment]
Which elements?

I have the wallet installed on Windows and Mac and I have no issues with remembering the window size and position.

**Comment by vRobM** [comment]
This is on Win10 for me.

The left hand menu adjusts in size, but the right side could use some tweaks. 
On a mac now and can't get it to run to look at specifics. More tonight.
