### ISSUE TITLE
Ark app wants to connect to tycho.usno.navy.mil on TCP port 80 (http)

### ISSUE THREAD

**Issue by vRobM** [ArkEcosystem/desktop-wallet#531]
why?

**Comment by Nasicus** [comment]
It's used for a [time service](https://github.com/ArkEcosystem/ark-desktop/blob/master/client/app/src/services/time.service.js#L12)

**Comment by vRobM** [comment]
I know, there are better ways to do this than routing peoples traffic to .mil TLD domains.
Why route everyone on the planet to a single NTP server?
There are proper pool addresses to use for closest time services across the planet.
