### ISSUE TITLE
Ark desktop wallet blank white screen.

### ISSUE THREAD

**Issue by Cal-Naughton-JR** [ArkEcosystem/desktop-wallet#538]
I recently downloaded the desktop wallet, and when opened there was nothing but a blank white screen with the "application" & "edit" toolbars in the top left corner of the screen. I restarted my computer, uninstalled & reinstalled the wallet, and disabled screenshot protection. None of this helped. Still all I see is a blank white or black page. Any help with this would be much appreciated.

**Comment by Nasicus** [comment]
When the window is open can you open the dev tools: `CTRL + D`  or `Edit - Open Dev Tools` and see if anything is there?
If not leave the dev tool window open and restart the app (`CTRL + R` or `Application - Restart`) and see if now anything is there.

**Comment by Cal-Naughton-JR** [comment]
The window for Open Dev Tools won't even open. I did try refreshing / restarting after clicking Open Dev Tools, but still no luck.

**Comment by j-a-m-l** [comment]
Which OS are you using?
Do you see the loading screen?

**Comment by Cal-Naughton-JR** [comment]
Windows 10 and no loading screen.

**Comment by Nasicus** [comment]
Do you have Chrome installed? If not could you install it and try again? (Normally this should not be an issue though and this is just a wild guess...)

**Comment by Nasicus** [comment]
Just installed ark-desktop on my girlfriends laptop and it happens to.
Interesting to note is, that it's why but I think the functionality is there, i.e. I clicked on the position where I knew a link is (the link to the release news) and it worked.
I'll try to find out more.

**Comment by Nasicus** [comment]
Ok for now I can at least tell you a workaround:

## Workaround
Go to the place where you the "Shortcut" to your ARK Client is.
Usually this is `C:\ProgramData\Microsoft\Windows\Start Menu\Programs`
Now right click on `Ark Client` and select `Properties`, click on the tab `Compatibility `. Click the checkbox  `Run this program in compatibility mode for:` and choose `Windows 8` or `Windows 7` (both appear to work)
It should now work. Note that it appears to be quite slow, at least where I'm trying.

==========

Some other findings:
Funny enough when the application starts blank / black you can choose "Print Page" save it to the PDF and it prints the actual UI which you should see.

**Comment by j-a-m-l** [comment]
@Cal-Naughton-JR has that workaround worked for you?

**Comment by luciorubeens** [comment]
@alexbarnsley Yes, due to a security vulnerability

**Comment by alexbarnsley** [comment]
@luciorubeens do you think it's worth a quick build with the previous version of electron that we used to use? Just to rule it out 🤔 I'm not at my machine to do a build at the minute unfortunately. I may be able to in a few hours though

**Comment by Nasicus** [comment]
Wonder if it's related to #475 .

In the meantime I tried deactivating UAC (completely via registry), but this changes nothing.
Any other ideas what I could try?

**Comment by Cal-Naughton-JR** [comment]
I appreciate the help! I will check here in the next few hours (away from my laptop currently). Sounds like you've got it somewhat figured out.

**Comment by Cal-Naughton-JR** [comment]
I had to change to windows 7 in compatibility mode. All seems to be working now though.

**Comment by Nasicus** [comment]
@Cal-Naughton-JR glad to hear it works for now!

---

@devs

So in the meantime I tried the following:
Upgraded some packages in package.json:
```
    "electron-builder": "^19.55.2",
    "electron-rebuild": "^1.7.3",
```
and rebuilt via `npm run dist:win` & installed this
=> same problem

Installed 1.4 => same problem
Installed 1.3.1 => same problem

**Comment by Nasicus** [comment]
Ok now I have a REALLY good workaround, which doesn't make the client slow!
---
## Workaround
Go to the place where you the "Shortcut" to your ARK Client is.
Usually this is `C:\ProgramData\Microsoft\Windows\Start Menu\Programs`
Now right click on `Ark Client` and select `Properties`, click on `Shortcut`.
Now in the `Target` field append the argument ` --disable-gpu`.
The whole `Target` field should look like this:
`"C:\Program Files\ArkClient\ArkClient.exe" --disable-gpu`

If you do this it should work AND be fast!
Can you try this @Cal-Naughton-JR ? (Don't forget to disable the compatibility again).
---

@devs
No idea how to fix this though. Maybe we could just install a second shortcut which contains this additional argument or something like this.

**Comment by zillionn** [comment]
Is this 1.5.1 issue or with every version?

**Comment by Nasicus** [comment]
Pretty sure it's for every version. I tried a lot of versions (until 2.x) and the blank screen happened everywhere.

**Comment by zillionn** [comment]
Well it's obviously something with your computers/GPUs, I have it installed on Windows 10 and got no issues whatsoever. Try to update your GPU drivers.
