### ISSUE TITLE
Send dialog remembers values

### ISSUE THREAD

**Issue by Nasicus** [ArkEcosystem/desktop-wallet#553]
Since the send-form dialog was refactored it somehow and only sometimes remebers addresses which you put in, e.g.:

![resolve](https://user-images.githubusercontent.com/1086065/35768608-98bc4f38-08fe-11e8-9293-dff7bd7e227f.gif)

Not only was this probably not intended but it also doesn't work since you cannot click "Next" even though the address is already there and if you can click next it gives an exception :P

I tried to fix it, but didn't find a good solution yet.
I think it has something to do with the fact, that the `$scope` of the dialog is not "dismissed" anymore when it's closed? Maybe a solution would be to ensure the `$scope` is "cleaned" when the dialog is opened (or by simply opening a new (sub)$scope?

@j-a-m-l do you know what to do?

**Comment by j-a-m-l** [comment]
uhmm, that may work.
