### ISSUE TITLE
ArkClient 1.5.1 (Windows version) disables USB keyboard

### ISSUE THREAD

**Issue by zbig001** [ArkEcosystem/desktop-wallet#570]
I have a problem with ArkClient on stationary PC with Windows 7 64-bit Home installed.
USB keyboard becomes inactive after a couple of seconds (to one minute max.) after opening ArkClient window.
Only USB mouse is resistant to this bug.
Attempting to connect keyboard to different USB ports not helped.
ArkClient was used in combination with ledger nano s.

**Comment by alexbarnsley** [comment]
If you take out your ledger and try using the wallet in the same way, do you have the same problem?

**Comment by zbig001** [comment]
Without ledger problem appeared the same.

**Comment by boldninja** [comment]
I'm gonna close this issue if you still having this issue please re-open it. Make sure to use the latest version of the Desktop wallet available at : https://github.com/ArkEcosystem/desktop-wallet/releases
