### ISSUE TITLE
Add "http://" as hint for Seed node text box when adding a new network

### ISSUE THREAD

**Issue by vRobM** [ArkEcosystem/desktop-wallet#571]
Maybe prepopulate the text box with it?

**Comment by Nasicus** [comment]
Added a placeholder, is this enough for you?

![image](https://user-images.githubusercontent.com/1086065/36339722-257f9eb6-13cc-11e8-9686-79010a2b305a.png)

**Comment by vRobM** [comment]
I wouldn't use 'my' , just http://x.x.x.x:4001
Would it be easy to pre-populate the field with http:// so folks don't have to type it in?

**Comment by Nasicus** [comment]
Changed it to your suggestion.

And yes it would be easy.
However I disagree with it, because then the field already has a value and therefore the "Next" button would be visible earlier.
However I will add a validation to the field that always and URL with either `http` or `https` is entered.
