### ISSUE TITLE
Can't vote with Ledger

### ISSUE THREAD

**Issue by Razican** [ArkEcosystem/desktop-wallet#594]
So, I'm using versions 1.4.3, 1.5.1 and latest git code, and I can't vote with the Ledger wallet. This means I basically have no use for the currency. When I click to sign with the wallet, it just closes the pop-up and nothing happens. I'm on Linux.

**Comment by luciorubeens** [comment]
Hey @Razican, sorry my late reply. Did you solve it?

**Comment by Razican** [comment]
I solved it by using the release binaries, but I couldn't compile it myself from source.

**Comment by luciorubeens** [comment]
Yes, it's pretty annoying to compile the node-hid. I updated it recently to the last version, if you still have interest maybe this will help:

- Fetch last commit.
- Install nvm.
- Run `nvm use` in the source directory.
- Run `rm -rf node_modules client/node_modules client/app/dependencies.min.js && npm install`.

I hope it works 😅
