### ISSUE TITLE
Privacy concerns with Changelly integration

### ISSUE THREAD

**Issue by katomm** [ArkEcosystem/desktop-wallet#603]
Hello,
as soon as the wallet opens, it looks like it does load the iframe of the Changelly widget. (Even if you do not want to use it or click the tab) 

If an user has some kind of personal firewall installed it will look like the wallet opens connections to:
 google.com
 ssl-google.analytics.l.google.com
 platform-lookaside.fbsbx.com 
 facebook.com
 yandex.ru
 doubleblick.net
 and maybe others
 
 Not something you would expect from a wallet - jeopardising users trust. A better way would be ~~removing Changelly completely~~ not loading the iframe until someone clicks on the tab.

**Comment by j-a-m-l** [comment]
This was fixed by #604. In some minutes/hours it'd be available.
