### ISSUE TITLE
Trojan in ArkClient-Ubuntu-1.6.0_amd64 (1).deb ?

### ISSUE THREAD

**Issue by Animo11** [ArkEcosystem/desktop-wallet#609]
I just checked the ArkClient-Ubuntu-1.6.0_amd64 (1).deb file I downloaded on 28-06  it gives two warnings on Virustotal.
Avast
ELF:Agent-RA [Trj]
AVG
ELF:Agent-RA [Trj]
I always verify hash and use Virustotal before installing so I know this was not the case in June.
If I download again I got same result,false positive???

**Comment by boldninja** [comment]
This looks like a false positive. I just double checked uploading:

https://www.virustotal.com/#/file/25a5e83d0ae86097c713b852e24359b926620c0b01779d3ef0cab7b60751feb9/detection

Can you compare your SHA256 with this legit one?

**Comment by Animo11** [comment]
Already did and they match,is same SHA256 for both downloads(the version I downloaded on 28-06 and today).I just wanted to notify  because I got no false positive in June.Don't find much info about ELF:Agent-RA [Trj] on Google and was a bit worried.

**Comment by j-a-m-l** [comment]
@boldninja Could this be closed?

**Comment by boldninja** [comment]
Yes
