### ISSUE TITLE
Signing a tx on windows client

### ISSUE THREAD

**Issue by axenter** [ArkEcosystem/desktop-wallet#618]
Signing a tx on the windows desktop client when using a non ledger address ask for ledger to sign after one tx has been signed. Requires a restart to be able to sign a new tx again.

**Comment by boldninja** [comment]
@j-a-m-l  can you try to reproduce this?

**Comment by j-a-m-l** [comment]
OK.

@axenter what Windows version are you using?
When you say "to sign after one tx has been signed" do you mean that you signed a transaction with a Ledger, remove it, and then you tried to sign a transaction with a different address?

**Comment by axenter** [comment]
Still a bug in the new version. (latest and the one before that used)

Sending a tx from a non ledger address so normall address will ask for a ledger confirm for the second tx.

**Comment by axenter** [comment]
Not a bug @gerard doesn't know how blockchains work :')

**Comment by boldninja** [comment]
Tagged wrong Gerard 🤣

**Comment by j-a-m-l** [comment]
The creator of the issue has asked me to close it.
