### ISSUE TITLE
#HELP Lost MAINNET accounts

### ISSUE THREAD

**Issue by vRobM** [ArkEcosystem/desktop-wallet#621]
In testing DEVNET after the reboot of the chain, had some issues getting the wallet to work correctly.

After removing the DEVNET network and creating a new one, the MAINNET got corrupted somehow. Now MAINNET is blank with no accounts even though it has a network configuration listed.

Reload, restart, network swap all do nothing to resolve. The data for MAINNET, I have a feeling, has lost it's index or address associations when the DEVNET network was removed.

I'd like to attempt recovery of the accounts before I go looking for all the pass phrases, contacts and folder structures.

I need some help and guidance on where to look and get started. Ping me on Slack @rob in #help PST

**Comment by fix** [comment]
mmm looks like corruption. Can you audit the storage:
- ctrl+D
- check Application tab -> local storage

copy and paste here the content o `global_mainnet`

**Comment by zillionn** [comment]
This happened to me twice.

**Comment by vRobM** [comment]
{"marketTicker":{"ARK":{"symbol":"ARK","currencies":{"BTC":{"price":0.0001336,"marketCap":14003.972574399999,"volume":168.05271906235916,"timestamp":1535565174,"change24h":3.807303807303794},"AUD":{"price":1.283790456,"marketCap":134567113.30165023,"volume":1634330.5648469087,"timestamp":1535564491,"change24h":3.807303807303812},"BRL":{"price":3.8291096,"marketCap":401367857.9548784,"volume":4874651.33128293,"timestamp":1535565126,"change24h":3.8073038073038052},"CAD":{"price":1.27085664,"marketCap":133211388.71672256,"volume":1617865.1590557117,"timestamp":1535565176,"change24h":3.807303807303814},"CHF":{"price":0.9221236,"marketCap":96657137.75903441,"volume":1173910.2569295506,"timestamp":1535555745,"change24h":3.9872408293460846},"CNY":{"price":6.26998828,"marketCap":657221137.0877951,"volume":7982014.073514733,"timestamp":1535563795,"change24h":3.807303807303793},"EUR":{"price":0.802284032,"marketCap":84095535.78598092,"volume":1021348.3898856896,"timestamp":1535565198,"change24h":3.8073038073037906},"GBP":{"price":0.721959704,"marketCap":75675927.35507442,"volume":919091.4337464329,"timestamp":1535565189,"change24h":3.8073038073037866},"HKD":{"price":7.338802976,"marketCap":769254458.1199783,"volume":9342669.558735413,"timestamp":1535556450,"change24h":3.807303807303799},"IDR":{"price":13679.4376,"marketCap":1433880755865.3904,"volume":17414620022.37851,"timestamp":1535564872,"change24h":3.8073038073038017},"INR":{"price":63.823392,"marketCap":6689977778.242368,"volume":81250425.10660763,"timestamp":1535563743,"change24h":3.807303807303799},"JPY":{"price":104.618308312,"marketCap":10966107188.48332,"volume":133184429.06143476,"timestamp":1535565188,"change24h":3.8073038073038106},"KRW":{"price":1050,"marketCap":110061161700,"volume":1329671548.1026878,"timestamp":1535565059,"change24h":4.477611940298507},"MXN":{"price":17.568408016,"marketCap":1841523233.7719543,"volume":22365477.217919305,"timestamp":1535565164,"change24h":3.8073038073037995},"RUB":{"price":63.850730568,"marketCap":6692843411.150268,"volume":81285228.49455364,"timestamp":1535565164,"change24h":3.8073038073038155},"USD":{"price":0.939587424,"marketCap":98487698.4801433,"volume":1196142.593374266,"timestamp":1535565193,"change24h":3.8073038073037955}},"timestamp":1535565201362}},"language":"en","peers":[{"ip":"217.182.84.106","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-133-generic","height":5611088,"status":"OK","delay":12},{"ip":"51.38.106.217","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-133-generic","height":5611088,"status":"OK","delay":26},{"ip":"193.70.112.227","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-130-generic","height":5611088,"status":"OK","delay":28},{"ip":"80.208.224.58","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-133-generic","height":5611088,"status":"OK","delay":122},{"ip":"207.246.90.238","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-119-generic","height":5611088,"status":"OK","delay":146},{"ip":"5.39.9.240","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-104-generic","height":5611087,"status":"OK","delay":19},{"ip":"104.248.29.128","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-134-generic","height":5611087,"status":"OK","delay":29},{"ip":"217.160.169.226","port":4001,"version":"1.1.0","errors":0,"os":"linux4.15.0-29-generic","height":5611087,"status":"OK","delay":38},{"ip":"5.39.9.241","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-104-generic","height":5611087,"status":"OK","delay":61},{"ip":"5.39.9.242","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-104-generic","height":5611087,"status":"OK","delay":77},{"ip":"5.39.9.251","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-104-generic","height":5611087,"status":"OK","delay":84},{"ip":"144.217.86.185","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-134-generic","height":5611087,"status":"OK","delay":169},{"ip":"172.104.190.150","port":4001,"version":"1.0.3","errors":0,"os":"linux4.15.13-x86_64-linode106","height":5611087,"status":"OK","delay":686},{"ip":"51.255.81.175","port":4001,"version":"1.0.2","errors":0,"os":"linux4.4.0-103-generic","height":5611086,"status":"OK","delay":9},{"ip":"54.38.119.241","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-112-generic","height":5611086,"status":"OK","delay":17},{"ip":"176.103.48.37","port":4001,"version":"1.0.3","errors":0,"os":"linux3.16.0-6-amd64","height":5611086,"status":"OK","delay":105},{"ip":"144.217.243.108","port":4001,"version":"1.0.1","errors":0,"os":"linux4.4.0-128-generic","height":5611086,"status":"OK","delay":172},{"ip":"94.16.120.204","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-128-generic","height":5611086,"status":"OK","delay":1024},{"ip":"54.38.119.242","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-112-generic","height":5611085,"status":"OK","delay":11},{"ip":"209.250.230.44","port":4001,"version":"1.0.2","errors":0,"os":"linux4.13.0-32-generic","height":5611085,"status":"OK","delay":16},{"ip":"193.31.24.106","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-131-generic","height":5611085,"status":"OK","delay":33},{"ip":"45.77.60.164","port":4001,"version":"1.0.2","errors":0,"os":"linux4.4.0-128-generic","height":5611085,"status":"OK","delay":35},{"ip":"209.250.239.104","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-134-generic","height":5611085,"status":"OK","delay":37},{"ip":"5.39.9.244","port":4001,"version":"1.1.0","errors":3,"os":"linux4.4.0-104-generic","status":"OK","delay":37},{"ip":"91.134.115.30","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-112-generic","height":5611085,"status":"OK","delay":39},{"ip":"158.69.59.90","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-127-generic","height":5611085,"status":"OK","delay":165},{"ip":"142.44.212.7","port":4001,"version":"1.1.0","errors":0,"os":"linux4.9.77-xxxx-std-ipv6-64","height":5611085,"status":"OK","delay":172},{"ip":"45.32.41.4","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-128-generic","height":5611085,"status":"OK","delay":481},{"ip":"138.68.68.66","port":4001,"version":"1.1.0","errors":0,"os":"linux4.13.0-38-generic","height":5611084,"status":"OK","delay":36},{"ip":"35.231.197.124","port":4001,"version":"1.0.3","errors":0,"os":"linux4.15.0-1014-gcp","height":5611084,"status":"OK","delay":189},{"ip":"213.32.9.96","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-112-generic","height":5611083,"status":"OK","delay":15},{"ip":"188.166.124.235","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-133-generic","height":5611083,"status":"OK","delay":28},{"ip":"178.32.187.79","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-133-generic","height":5611083,"status":"OK","delay":29},{"ip":"185.183.156.115","port":4001,"version":"1.0.2","errors":0,"os":"linux4.4.0-134-generic","height":5611083,"status":"OK","delay":36},{"ip":"199.247.0.180","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-134-generic","height":5611083,"status":"OK","delay":43},{"ip":"142.93.69.152","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-131-generic","height":5611083,"status":"OK","delay":151},{"ip":"45.32.234.71","port":4001,"version":"1.0.2","errors":0,"os":"linux4.4.0-104-generic","height":5611083,"status":"OK","delay":162},{"ip":"216.245.209.178","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-131-generic","height":5611083,"status":"OK","delay":221},{"ip":"139.162.45.18","port":4001,"version":"1.0.3","errors":0,"os":"linux4.15.13-x86_64-linode106","height":5611083,"status":"OK","delay":611},{"ip":"104.238.189.78","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-131-generic","height":5611083,"status":"OK","delay":713},{"ip":"167.99.41.75","port":4001,"version":"1.1.0","errors":0,"os":"linux4.13.0-38-generic","height":5611082,"status":"OK","delay":18},{"ip":"94.16.121.39","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-130-generic","height":5611082,"status":"OK","delay":29},{"ip":"94.16.114.182","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-130-generic","height":5611082,"status":"OK","delay":55},{"ip":"83.136.250.247","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-134-generic","height":5611082,"status":"OK","delay":78},{"ip":"45.77.145.168","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-131-generic","height":5611082,"status":"OK","delay":149},{"ip":"104.131.43.220","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-116-generic","height":5611082,"status":"OK","delay":155},{"ip":"172.104.21.209","port":4001,"version":"1.0.3","errors":0,"os":"linux4.15.13-x86_64-linode106","height":5611082,"status":"OK","delay":155},{"ip":"108.41.250.128","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-128-generic","height":5611082,"status":"OK","delay":188},{"ip":"207.246.80.255","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-109-generic","height":5611082,"status":"OK","delay":687},{"ip":"91.134.115.26","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-131-generic","height":5611081,"status":"OK","delay":9},{"ip":"51.255.25.225","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-134-generic","height":5611081,"status":"OK","delay":29},{"ip":"188.165.177.34","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-133-generic","height":5611081,"status":"OK","delay":42},{"ip":"91.121.181.198","port":4001,"version":"1.0.2","errors":0,"os":"linux4.9.116-xxxx-std-ipv6-64","height":5611081,"status":"OK","delay":49},{"ip":"163.172.52.237","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-131-generic","height":5611081,"status":"OK","delay":57},{"ip":"54.36.121.115","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-103-generic","height":5611081,"status":"OK","delay":59},{"ip":"37.59.70.164","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-96-generic","height":5611081,"status":"OK","delay":65},{"ip":"51.15.81.10","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.38-std-1","height":5611081,"status":"OK","delay":72},{"ip":"92.222.167.232","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-134-generic","height":5611081,"status":"OK","delay":84},{"ip":"94.16.113.29","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-131-generic","height":5611081,"status":"OK","delay":93},{"ip":"5.45.100.132","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-134-generic","height":5611081,"status":"OK","delay":94},{"ip":"185.162.248.192","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-112-generic","height":5611081,"status":"OK","delay":96},{"ip":"94.130.71.41","port":4001,"version":"1.1.0","errors":0,"os":"linux4.13.0-26-generic","height":5611081,"status":"OK","delay":97},{"ip":"83.136.254.44","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-133-generic","height":5611081,"status":"OK","delay":100},{"ip":"140.82.43.128","port":4001,"version":"1.0.3","errors":0,"os":"linux4.13.0-46-generic","height":5611081,"status":"OK","delay":151},{"ip":"45.79.172.169","port":4001,"version":"1.0.3","errors":0,"os":"linux4.17.8-x86_64-linode110","height":5611081,"status":"OK","delay":157},{"ip":"212.24.101.114","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-130-generic","height":5611081,"status":"OK","delay":161},{"ip":"159.65.243.144","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-130-generic","height":5611081,"status":"OK","delay":183},{"ip":"45.77.146.17","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-83-generic","height":5611081,"status":"OK","delay":183},{"ip":"165.227.40.144","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-131-generic","height":5611081,"status":"OK","delay":186},{"ip":"45.33.77.188","port":4001,"version":"1.0.3","errors":0,"os":"linux4.17.15-x86_64-linode115","height":5611081,"status":"OK","delay":187},{"ip":"45.76.20.244","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-133-generic","height":5611081,"status":"OK","delay":209},{"ip":"176.103.48.24","port":4001,"version":"1.0.3","errors":0,"os":"linux3.16.0-4-amd64","height":5611081,"status":"OK","delay":215},{"ip":"149.28.116.190","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-128-generic","height":5611081,"status":"OK","delay":219},{"ip":"45.76.226.73","port":4001,"version":"1.1.0","errors":0,"os":"linux4.13.0-46-generic","height":5611081,"status":"OK","delay":220},{"ip":"45.76.26.69","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-134-generic","height":5611081,"status":"OK","delay":226},{"ip":"45.77.195.245","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-104-generic","height":5611081,"status":"OK","delay":231},{"ip":"198.204.247.123","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-128-generic","height":5611081,"status":"OK","delay":236},{"ip":"149.28.243.54","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-130-generic","height":5611081,"status":"OK","delay":249},{"ip":"185.24.218.50","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-131-generic","height":5611081,"status":"OK","delay":277},{"ip":"173.233.75.2","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-127-generic","height":5611081,"status":"OK","delay":290},{"ip":"207.246.96.193","port":4001,"version":"1.0.2","errors":0,"os":"linux4.4.0-109-generic","height":5611081,"status":"OK","delay":296},{"ip":"192.99.91.205","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.59-1-pve","height":5611081,"status":"OK","delay":307},{"ip":"104.238.181.217","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-101-generic","height":5611081,"status":"OK","delay":411},{"ip":"45.79.165.238","port":4001,"version":"1.0.3","errors":0,"os":"linux4.15.13-x86_64-linode106","height":5611081,"status":"OK","delay":447},{"ip":"199.247.6.35","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-130-generic","height":5611081,"status":"OK","delay":486},{"ip":"37.120.178.207","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-134-generic","height":5611081,"status":"OK","delay":494},{"ip":"54.38.48.172","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-127-generic","height":5611080,"status":"OK","delay":77},{"ip":"5.39.9.249","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-127-generic","height":5611079,"status":"OK","delay":45},{"ip":"5.39.9.247","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-93-generic","height":5611079,"status":"OK","delay":61},{"ip":"5.39.9.245","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-104-generic","height":5611079,"status":"OK","delay":65},{"ip":"5.39.9.250","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-104-generic","height":5611079,"status":"OK","delay":68},{"ip":"54.38.48.161","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-127-generic","height":5611079,"status":"OK","delay":154},{"ip":"54.38.48.163","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-127-generic","height":5611079,"status":"OK","delay":311},{"ip":"5.39.9.243","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-104-generic","height":5611078,"status":"OK","delay":17},{"ip":"209.250.233.136","port":4001,"version":"1.0.2","errors":0,"os":"linux4.4.0-134-generic","height":5610926,"status":"OK","delay":1210},{"ip":"104.238.173.75","port":4001,"version":"1.1.0","errors":0,"os":"linux4.4.0-98-generic","height":5562561,"status":"OK","delay":25},{"ip":"149.28.61.39","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-128-generic","height":5237126,"status":"OK","delay":416},{"ip":"207.148.8.74","port":4001,"version":"1.0.3","errors":0,"os":"linux4.4.0-109-generic","height":5213096,"status":"OK","delay":196},{"ip":"35.184.151.159","port":4001,"version":"1.0.2","errors":0,"os":"linux4.13.0-1015-gcp","height":4788441,"status":"OK","delay":243},{"ip":"94.23.250.111","port":4001,"version":"1.0.2","errors":0,"os":"linux3.14.32-xxxx-grs-ipv6-64","height":4787756,"status":"OK","delay":19},{"ip":"52.35.9.191","port":4001,"version":"1.0.2","errors":0,"os":"linux4.4.0-1044-aws","height":4782546,"status":"OK","delay":336},{"ip":"213.136.93.24","port":4001,"version":"1.0.0","errors":0,"os":"linux4.4.0-71-generic","height":2009214,"status":"OK","delay":1916}]}

**Comment by vRobM** [comment]
Looking at it, there is another entry below it, called `storage-undefined` that seems to have my addresses in it.

rename the mainnet and make undefined mainnet?

**Comment by vRobM** [comment]
yes? no?

**Comment by vRobM** [comment]
I can't do anything from that context anyway.. the only action is a refresh.. so what do we do now?

find out how something like that gets corrupted? may not be worth the time in v1
detect an undefined wallet and repair it? would need a new build.
how to manually repair this?
I found the file__0.localstorage file that appears to be a SQLite DB, but there are a few others.

**Comment by vRobM** [comment]
I still need help resolving this

**Comment by vRobM** [comment]
copying the contents of storage-undefined to storage-mainnet doesn't produce any changes. 
no addresses show up in the wallet.

**Comment by vRobM** [comment]
since there was no followup, a complete reinstall & reimport was required.
