### ISSUE TITLE
Wallet to check NTP, internet time sync at point of opening wallet.

### ISSUE THREAD

**Issue by jamiec79** [ArkEcosystem/desktop-wallet#624]
Could the Ark desktop wallet perform a check on Internet time when you open it each time.

If NTP time is out of sync locally, then flag to user to update before proceeding?

Thanks

**Comment by j-a-m-l** [comment]
Thanks for the idea. We may include it on the new version of the wallet.

**Comment by alexbarnsley** [comment]
@j-a-m-l 	a better way may be to offset all transaction timestamps based on the ntp offset, that way the user doesn't have to do anything on their machine at all

**Comment by jamiec79** [comment]
Cool thx for the reply :)
