### ISSUE TITLE
Contacts just display a amount of zero

### ISSUE THREAD

**Issue by reConNico** [ArkEcosystem/desktop-wallet#630]
**Describe the bug**
In the new v2 desktop wallet the contacts just show an amount of zero. Both on the listing and the detail page of the contacts.

**To Reproduce**
1. Go to 'My contacts'
2. Create a new contact (example address: AUDud8tvyVZa67p3QY7XPRUTjRGnWQQ9Xv)
3. See error (both on listing and detail of contact)

**Expected behavior**
The correct amount of the wallet should be displayed.

**Screenshots**
![v2_contacts](https://user-images.githubusercontent.com/15830979/49402478-4742c980-f74a-11e8-9a41-6cf7cb09bd17.png)
![v2_contact](https://user-images.githubusercontent.com/15830979/49402483-490c8d00-f74a-11e8-8626-69d84394ccd7.png)

**Server**
 - OS: Ubuntu
 - Version 18.04

**Additional context**
nothing more to complain about

**Comment by sleepdefic1t** [comment]
Just Ledger addresses appear to be ```0``` for myself, @vmunich & @zillionn in macOS.
_**(#632 & #634 )**_

Our systems appear to all be:
- OS: Mac OS
- Version: Mojave 10.14.1

Is this all contact addresses on your Ubuntu machine?

**Comment by alexbarnsley** [comment]
Resolved in #650
