### ISSUE TITLE
Ledger White Screen

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/desktop-wallet#631]
**Describe the bug**
Ledger Nano S doesn't work.

**To Reproduce**
1. Open Wallet
2. Plugin Ledger nano S
3. Enter Pin
4. Click Ark Logo
5. Screen turns white

**Expected behavior**
Use wallets on ledger

**Screenshots**
-

**Server (please complete the following information):**
 - OS: Windows 
 - Version 10

**Additional context**
Ledger works without problems on the old wallet.

**Comment by alexbarnsley** [comment]
@Jarunik please open the developer tools and copy the error, if there is one

**Comment by Jarunik** [comment]
Found the problem. Firmware needs to be at least 1.4.2.
