### ISSUE TITLE
Total Balance doesn't account for Ledger wallet's balances

### ISSUE THREAD

**Issue by vmunich** [ArkEcosystem/desktop-wallet#632]
**Describe the bug**
The Total Balance on the top of the wallet doesn't account for Ledger wallet's balances.

**Expected behavior**
It should be a sum of the balance of every wallet loaded on the Desktop Wallet.

**Screenshots**
![screenshot](https://i.gyazo.com/3f567dec3837fc2783b80533b61aeff0.png)

**Server (please complete the following information):**
 - OS: OSX 10.14.1

**Comment by sleepdefic1t** [comment]
#634 also notes Ledger address balances as ```0```.
