### ISSUE TITLE
Can't change the peer

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/desktop-wallet#633]
**Describe the bug**
I can see my accounts' transactions but the peer is `None` and can't change it.

**Screenshots**
<img width="523" alt="screenshot 2018-12-04 at 00 04 46" src="https://user-images.githubusercontent.com/3462869/49404492-43b63f00-f758-11e8-971d-f2a2eac04408.png">

**Server (please complete the following information):**
 - OS: Mac OS
 - Version: Mojave 10.14.1

**Comment by sleepdefic1t** [comment]
Can confirm Mainnet peer issue.

Interestingly, Devnet shows peers status and allows changing peers.

<img width="379" alt="screen shot 2018-12-03 at 2 35 33 pm" src="https://user-images.githubusercontent.com/7477456/49405870-bac3e700-f708-11e8-910a-bbfa949094f1.png">


- OS: Mac OS
- Version: Mojave 10.14.1

**Comment by ItsANameToo** [comment]
Should be fixed by https://github.com/ArkEcosystem/javascript-client/pull/9

**Comment by sleepdefic1t** [comment]
ArkEcosystem/javascript-client#9 should resolve it 👍 
Nice find @ItsANameToo 

In the mean time, adding a peer manually seems to work fine on my system.  

<img width="390" alt="screen shot 2018-12-03 at 2 39 26 pm" src="https://user-images.githubusercontent.com/7477456/49406219-cbc12800-f709-11e8-951d-3d840199b051.png">

<img width="392" alt="screen shot 2018-12-03 at 2 38 52 pm" src="https://user-images.githubusercontent.com/7477456/49406226-cfed4580-f709-11e8-86ee-67a4e775a869.png">


- OS: Mac OS
- Version: Mojave 10.14.1

**Comment by ItsANameToo** [comment]
Credits go to @alexbarnsley :)

**Comment by alexbarnsley** [comment]
Resolved in #643
