### ISSUE TITLE
Currency settings

### ISSUE THREAD

**Issue by maisonark** [ArkEcosystem/desktop-wallet#640]
**Describe the bug**
When changing the currency at the left panel (gear icon) it will not be saved for next time like other options such dark-theme do stay saved. 

**Additional context**
I'm using the win64 version

**Comment by j-a-m-l** [comment]
Thanks @maisonark .

It could confuse some users, although it was done on purpose. But, since the theme is persisted after the session, then clearly, the currency should work the same way.
