### ISSUE TITLE
Choose which sounds would be played on events 

### ISSUE THREAD

**Issue by j-a-m-l** [ArkEcosystem/desktop-wallet#641]
Initially we could, either provide some sounds (like #639) or not, so this feature would be enabled only if the user has selected the sounds.

 * Play a sound at different events:
   - Receiving transactions
 * Those sounds could be disabled too.
 * The user should have the option to choose the sounds.

**Comment by luciorubeens** [comment]
Implemented as a plugin: https://github.com/ark-ecosystem-desktop-plugins/sound-notifications
