### ISSUE TITLE
Can't see a wallet's public key unless it has sent transactions

### ISSUE THREAD

**Issue by vmunich** [ArkEcosystem/desktop-wallet#648]
**Describe the bug**
After creating a brand new wallet, or importing a wallet that has no transactions yet, there's no button to see its public key. 

**Screenshots**
![](https://i.gyazo.com/ad213c9aef9fcf764e02c4739110a6bd.png)

**Expected behavior**
![](https://i.gyazo.com/3e53875447c4e91ce5a5b1a1697177ad.png)

**Comment by boldninja** [comment]
That is normal behaviour.

**Comment by ItsANameToo** [comment]
We like you @vmunich and reopen this issue. We should be able to get it to work when importing a wallet by passphrase and when generating a new one.

**Comment by alexbarnsley** [comment]
who is this "we" @ItsANameToo? :danstop:

**Comment by vmunich** [comment]
tfw you find out @alexbarnsley doesn't like you through github comments 😢

**Comment by alexbarnsley** [comment]
only joking @vmunich :trollface:
