### ISSUE TITLE
Debian 9: ark-desktop-wallet (v2.0.0) is not working/functional

### ISSUE THREAD

**Issue by furiousxk** [ArkEcosystem/desktop-wallet#654]
### Steps to reproduce
1. Clean install Debian 9
2. Update system
3. install libudev-dev libusb-1.0-0-dev
4. Download Ark.Desktop-Wallet-amd64-2.0.0.deb
5. dpkg -i <package>
6. run ark-desktop-wallet

### Expected result
The wallet starts. If failed to start some output to stdout

### Actual result
Nothing happens

If i have forgotten any extra information or need to supply any additional information I will gladly do so.

Kind regards

**Comment by furiousxk** [comment]
> 
> 
> I've tried Debian 9 with the default installation and I needed to install additional packages:
> 
> ```
> sudo apt install gconf2 libappindicator1 libudev-dev libusb-1.0.0-dev libappindicator7 libdbusmenu-gtk4 libdbusmenu-glib4 pmisc
> ```
> 
> @furiousxk, would you mind to try it?

I'll give it a spin in a few hours, currently in office.
Either way, if the binary should throw some output to stdout. 

Will retest and report back by EOD GMT+1

**Comment by furiousxk** [comment]
> I've tried Debian 9 with the default installation and I needed to install additional packages:
> 
> ```
> sudo apt install gconf2 libappindicator1 libudev-dev libusb-1.0.0-dev libappindicator7 libdbusmenu-gtk4 libdbusmenu-glib4 pmisc
> ```
> 
> @furiousxk, would you mind to try it?

Could you share /etc/apt/sources.list

There is no such package as libappindicator7 according to my research
https://packages.debian.org/search?searchon=sourcenames&keywords=libappindicator

Same goes for pmisc

**Comment by j-a-m-l** [comment]
@furiousxk try `libindicator7` and `psmisc`

**Comment by furiousxk** [comment]
Does not work. No indicator of what went wrong or any debugging.
Any verbosity flag I can pass to ark-desktop-wallet or a log file or some sort?

Following packages are installed are installed on the system:
_Table below is output of dpkg-query -l <package>_

| Package | Version
|---|---
libappindicator1| 0.4.92-4
libappindicator3-1|0.4.92-4
libindicator3-7 |0.5.0-3+b1
libindicator7|0.5.0-3+b1
libusb-0.1.4|2:0.1.12-30
libusb-1.0-0|2:1.0.21-1
libusb-1.0-0-dev|2:1.0.21-1
libusb-1.0-doc|2:1.0.21-1
libudev-dev|232-25+deb9u6
gconf2|3.2.6-4+b1
libdbusmenu-gtk4|12.10.2-2
libdbusmenu-glib4|12.10.2-2
psmisc|22.21-2.1+b2

Output of uname -a
Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux

**Comment by furiousxk** [comment]
I'll have a look at the config and spin up a VM to set up the dev version some time this weekend.

I have another Debian 9 machine running the same kernel as you, i'll give that one a try as well and report back.

Thanks for the assistance so far.

**Comment by j-a-m-l** [comment]
OK, I'll keep this issue open while waiting for your feedback.

**Comment by j-a-m-l** [comment]
@furiousxk We've just published the `AppImage` version: https://github.com/ArkEcosystem/desktop-wallet/releases/tag/2.0.0

**Comment by furiousxk** [comment]
> 
> 
> @furiousxk We've just published the `AppImage` version: https://github.com/ArkEcosystem/desktop-wallet/releases/tag/2.0.0

Hi, I didn't get around to testing it last night. 

I'll test the new version on the 4.9.110-3 kernel tonight and check for 4.9.130-2 and the dev version tomorrow evening.

**Comment by j-a-m-l** [comment]
OK, could you check both releases (`deb` and `AppImage`) and the development version?

**Comment by furiousxk** [comment]
> 
> 
> OK, could you check both releases (`deb` and `AppImage`) and the development version?

Sure, will report back soon

**Comment by furiousxk** [comment]
.deb works fine on 4.9.130-2 after install packages mentioned above.
Will retest on older kernel soon, havent had a look at AppImage yet.

**Comment by j-a-m-l** [comment]
@furiousxk I'm going to close this issue, as it looks that there is at least 1 solution. If you think that something is missing, reopen it.
