### ISSUE TITLE
Open in explorer link pointing to incorrect address for sender of incoming transactions

### ISSUE THREAD

**Issue by moazzamak** [ArkEcosystem/desktop-wallet#657]
**Describe the bug**
Trying to view address in external browser doesn't open correct address.

**To Reproduce**
1. View an incoming transaction's details in v2 wallet
2. Click on the "Open in Explorer" link next to the sender's address
3. It will open wallet owner's address instead of sender address

**Expected behavior**
Link should point to sender's address

**Screenshots**
![image](https://user-images.githubusercontent.com/6873275/49475050-88081480-f816-11e8-877e-59eb3370096e.png)

**Server (please complete the following information):**
 - OS: Ubuntu
 - Version 16.04

**Additional context**

**Comment by ItsANameToo** [comment]
Thanks, should be fixed in #658
