### ISSUE TITLE
Transactions from AIP13 aren't filled in properly

### ISSUE THREAD

**Issue by vmunich** [ArkEcosystem/desktop-wallet#662]
**Describe the bug**
I have the following AIP13 compliant link: https://jsfiddle.net/0msew8n3/

When I click on it and tell my browser to open it on Ark Desktop Wallet, the Transfer fields are filled in, but the `Next` button is still disabled, even after entering my passphrase:

![](https://i.gyazo.com/66c0b229fee734fb50c6603d9f70c994.png)

If I delete a character from the `Recipient` field and type it again, the `Next` button gets enabled:

![](https://i.gyazo.com/a8ad476ccd464eeab3f51a2e9c6403a2.gif)

**To Reproduce**
1. Click on the `Send Transaction` link on https://jsfiddle.net/0msew8n3/
2. Open it with the Ark Desktop Wallet

**Expected behavior**
The next button should be enabled after typing my passphrase/password.

**Comment by ItsANameToo** [comment]
@alexbarnsley y u doing this issue :(

**Comment by alexbarnsley** [comment]
beginning to regret starting it @ItsANameToo 😂

**Comment by ItsANameToo** [comment]
isn't it as simple as doing a `touch()` on the input fields after they get filled @alexbarnsley ?

**Comment by alexbarnsley** [comment]
Already tried on mounted but didn't work: 
```
if (this.schema) {
  this.$refs.recipient.touch()
}
```

**Comment by ItsANameToo** [comment]
try it after the fields get filled in when it handles the AIP13 stuff

**Comment by alexbarnsley** [comment]
it is, since it's the data method that sets the fields:

![image](https://user-images.githubusercontent.com/8069294/49585572-a543fc80-f956-11e8-9fd1-62bfd6b6cf93.png)

schema is the data from the URI

**Comment by ItsANameToo** [comment]
🤔

**Comment by alexbarnsley** [comment]
I got to leave now so you can have a go @ItsANameToo

**Comment by ItsANameToo** [comment]
I can't get the link to open in the wallet, it always creates a new electron process so I can not do anything

**Comment by ItsANameToo** [comment]
Nevermind, it linked with the old repo checkout and tried to launch that as the wallet. So I can take a look at it now :D
