### ISSUE TITLE
White screen when restarting wallet after setting an invalid seed server

### ISSUE THREAD

**Issue by alessiodf** [ArkEcosystem/desktop-wallet#673]
**Describe the bug**
The wallet will no longer open (gets stuck on a white screen) if you set the seed server to an invalid or unresponsive peer.

**To Reproduce**
1. Go to Network Overview
2. Click on Ark
3. Change Seed Server to an invalid node e.g. http://8.8.8.8:4003
4. Save and restart wallet

**Expected behavior**
The wallet should still open but not connect if it can't connect to a peer

**Comment by alexbarnsley** [comment]
I've made a change in PR #680. This doesn't directly fix the white screen on reload of an invalid peer. What it does is when changing the seed server for a network, it validates the server to make sure it can connect and it also makes sure it can do a status check on the node.

**Comment by alessiodf** [comment]
Won't this mean you still get a white screen if the peer is valid at the time you change the seed server but is down when you open the wallet?

**Comment by alexbarnsley** [comment]
Yes it would. The PR I've opened doesn't address this area, which is why i've left the issue open.

**Comment by alessiodf** [comment]
:danstop:

**Comment by alexbarnsley** [comment]
:susp:

**Comment by ItsANameToo** [comment]
:whalessio:

**Comment by alexbarnsley** [comment]
🍿

**Comment by alessiodf** [comment]
MODS
