### ISSUE TITLE
URI scheme

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/desktop-wallet#738]
**Is your feature request related to a problem? Please describe.**
When I click on a link starting with `ark:`, the wallet opens up and shows an error message:
`Select a wallet and open the URI again`

**Describe the solution you'd like**
Is it that hard to set that URI to some variable and show a message like `Please choose a wallet.`. Then when I choose a wallet just check if there is such variable and open and populate the `Send` popup?

**Comment by zillionn** [comment]
Btw I get that error message only if my wallet is already open, if it's closed and I click on such a link, the wallet opens up but doesn't show any message.

**Comment by kalgoop** [comment]
I think that will come with Ark Pay

**Comment by alexbarnsley** [comment]
It's not hard, it's just not been done yet.

**Comment by kalgoop** [comment]
Maybe, simply we can store the uri till the user chooses the wallet and then automatically call the uri stored.

**Comment by kalgoop** [comment]
@alexbarnsley I'll work on it

**Comment by kalgoop** [comment]
@zillionn can you please check this out.
https://github.com/kalgoop/desktop-wallet/tree/patch-13
I think this should make it working. However, I was unable to test it.

When I click link starting with ark: nothing happens (even when the wallet is open)
Are you serving the application with 'yarn dev' or have you installed it ?

**Comment by alexbarnsley** [comment]
Resolved is #814
