### ISSUE TITLE
Price not sorting on dashboard wallet 2

### ISSUE THREAD

**Issue by TrueKhaos** [ArkEcosystem/desktop-wallet#744]
**Platform (please complete the following information):**
 - OS: Ubuntu 16.04 LTS
 - Version Desktop Wallet 2.0.0

**Describe the bug**

**How to reproduce the bug**
Steps to reproduce the behaviour:
1. Open Ark Desktop Wallet
2 . Look at the price graph, there are 3 decreasing prices listed on the left
3. See error price #2 = price #3

**Expected behaviour**
price#3 should be price#2 - 0.01

![arkwalletbug](https://user-images.githubusercontent.com/19697628/49985245-95867280-ff6b-11e8-88ac-d8c4924b86b4.png)

**Comment by ItsANameToo** [comment]
@zillionn this is just a rounding issue. Likely the scale is something in the range of 0.279, 0.274, 0.269 and will show up as 0.28, 0.27, 0.27

**Comment by j-a-m-l** [comment]
This is fixed on #750: now it uses more decimals if necessary
