### ISSUE TITLE
Changelly

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/desktop-wallet#754]
**Platform (please complete the following information):**
 - OS: macOs Mojave 10.14.1
 - Version: Desktop Wallet 2.1.0

**Describe the bug**
Not sure if I'm doing something wrong, but inside `Purchase ARK` when I click `EXCHANGE` a popup opens a webpage with text, just text:

<img width="942" alt="screenshot 2018-12-14 at 23 13 31" src="https://user-images.githubusercontent.com/3462869/50027776-17bb7900-fff6-11e8-8f26-16b850d9ae58.png">
<img width="912" alt="screenshot 2018-12-14 at 23 11 52" src="https://user-images.githubusercontent.com/3462869/50027734-f0fd4280-fff5-11e8-9144-79d28d3ffc0a.png">
<img width="912" alt="screenshot 2018-12-14 at 23 16 30" src="https://user-images.githubusercontent.com/3462869/50027842-53564300-fff6-11e8-8fc1-34837824b834.png">
<img width="912" alt="screenshot 2018-12-14 at 23 16 34" src="https://user-images.githubusercontent.com/3462869/50027852-56513380-fff6-11e8-94b5-7ee93dbc22fb.png">

Clicking `Buy now!` just scroll to the top of the page.

**Comment by luciorubeens** [comment]
It seems that Changelly did not allow purchases with fiat direct from the widget, as this behavior happens on [their own website](https://changelly.com/payment-widget).

**Comment by dated** [comment]
Definitely on Changellys side. Strangely enough some USD/Crypto pairings work as expected.

**Comment by j-a-m-l** [comment]
Clicking on "EXCHANGE" doesn't open the popup now
