### ISSUE TITLE
2nd passphrase

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/desktop-wallet#765]
**Platform (please complete the following information):**
 - macOS Mojave 10.14.2
 - Desktop Wallet 2.1.0

**Describe the bug**
2 issues:
- There is no way to register a `2nd passphrase` for less than `5 ARK`
- When click `Back` on the last screen, `Next` doesn't work anymore

**Expected behaviour**
To send a tx with my custom fee. 

**Screenshots**
<img width="693" alt="1" src="https://user-images.githubusercontent.com/3462869/50047301-1e5ff400-00bb-11e9-9d18-d9d0fa74003b.png">
<img width="543" alt="2" src="https://user-images.githubusercontent.com/3462869/50047303-228c1180-00bb-11e9-84f5-7b995e7256d7.png">

When get back, `Next` button is not clickable anymore:
<img width="683" alt="3" src="https://user-images.githubusercontent.com/3462869/50047305-26b82f00-00bb-11e9-8e35-049abd500897.png">

**Comment by ItsANameToo** [comment]
Fixed with #766
