### ISSUE TITLE
Delegate registration tx not showing as pending tx when unconfirmed

### ISSUE THREAD

**Issue by skeuo** [ArkEcosystem/desktop-wallet#774]
**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version (e.g. Desktop Wallet 2.1.1)

Description
Registering delegate with low fee results in no prompt unless confirmed. Will not show as unconfirmed pending transaction. 

Reproduction
Steps to reproduce the behaviour:
1. Register Delegate with fee of 0.0001 (with a wallet that has balance)
2. Wait for pending tx to appear in list assuming it goes unconfirmed due to fee being too low, should be zero prompting/feedback.

**Comment by zillionn** [comment]
I guess your fee is too low and the relay is not accepting it at all.

**Comment by zillionn** [comment]
You can check the API after sending the tx:
http://RELAY_IP:4003/api/v2/transactions/unconfirmed
