### ISSUE TITLE
creating my wallet

### ISSUE THREAD

**Issue by dukepath** [ArkEcosystem/desktop-wallet#777]
**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version (e.g. Desktop Wallet 2.1.0)

**Describe the bug**
I cannot finish the create a wallet process

**How to reproduce the bug**
Steps to reproduce the behaviour:
1. I get through the first few steps
2. I get to step 4...encryption
3. I enter in a new password
4. page freezes up

**Expected behaviour**
I've repeated this process several times and cannot get past it to the confirmation page

**Screenshots**

**Additional context**
Context about the problem here, such as screen resolution, error messages on the console (View > Toggle Developer Tools), or any other information that could be useful for reproducing and fixing the bug.

**Comment by alexbarnsley** [comment]
Hi @dukepath, could I just confirm that you're running Windows 10 on v2.1.0? That's based on you editing the "e.g." at the top of your issue. Thanks

**Comment by j-a-m-l** [comment]
@dukepath I've tried 2.1.0 on Windows 10 and it worked flawlessly. Would you mind to add more context:
 - Did you have previous wallets? how many?
 - When you say "page freezes up", can you click on the "Next" button of the step "4. Encryption" or is it after that, when clicking "Done" on the last step ("5. Confirmation")?

**Comment by dukepath** [comment]
Yes, I am running windows 10 on v2.1.0 and I've never had an ARK wallet before, I am trying to set one up for the first time.
 After I complete step 4 (Encryption) I hit the next button and nothing happens, the button seems to depress normally but nothing comes after that, I never get to the next step (5), I even tried clearing my cache and clearing my data on the ARK help tab and still does the same exact thing after I star the process all over again

**Comment by j-a-m-l** [comment]
@dukepath has you tried different passwords? could you try "example1+" (without quotes)?

**Comment by dukepath** [comment]
issue fixed.... my passphrase had quotations in it, I created a new passphrase without it and it went through just fine, thanks for your help

**Comment by j-a-m-l** [comment]
@dukepath which quotates were you using: " ' ` or other?

**Comment by dukepath** [comment]
“before and after my password” like that

**Comment by j-a-m-l** [comment]
Thank you.

I've tried it and it didn't produced any strange behaviour on Windows 10 or Ubuntu 18.04, so I'm going to close this issue.
