### ISSUE TITLE
Aggregate vote rewards, statistics dashboard

### ISSUE THREAD

**Issue by TwerkingGorilla** [ArkEcosystem/desktop-wallet#781]
**Problem:**
Since I like to support multiple delegates for their good work for the ecosystem, it has become difficult to track the voting rewards. Also I would be interested in statistics showing the rewards in comparison per wallet or delegate. 

** Solution:**
I would like to have a dashboard in the desktop wallet, that can show me per time frame per wallet (or voted delegate) what the return is, showing averages and also the cumulative. Line charts and pie charts would do the trick. Since delegate addresses are registered, I suspect it to be easy to track their transactions to your address automatically, and further add things up and provide statistics for all your wallets combined. For example pie charts showing percentages per voting weight per wallet or delegate, but also absolute amounts of Ark. Also line charts showing through time the what the reward income is per wallet, similar to coin marketcap top 10 coin price history.

**Comment by alexbarnsley** [comment]
Thank you for your issue report. We won't be including any highlighting of staking rewards from delegates within the wallet, as that implies it's part of the network whereas it's actually the delegates who provide that service to their voters. It may be possible to do in the future once we've figured out and implemented the plugin system, where third party plugins can be used.

**Comment by j-a-m-l** [comment]
Sorry, but the rewards are something that delegates are giving to their voters that it's outside our hands. We, as Ark Ecosystem, want to be clearly not tagged as a security, so we would never support this kind of features in our products.

In the near future we will add other features, such as transaction filtering, which could be useful for a lot of cases, so maybe you could use them to accomplish your goal.

**Comment by TwerkingGorilla** [comment]
Wow you guys are quick! Totally understandable. Hope the csv export functionality will return for the home page view too, so that you can export for all the wallets at once, that would help too.

All the best!
