### ISSUE TITLE
Ability to save and resend unconfirmed transactions offline

### ISSUE THREAD

**Issue by vmunich** [ArkEcosystem/desktop-wallet#785]
**Describe the solution you'd like**
Sometimes the wallet can connect to a bad peer, and transactions stay unconfirmed for a long time. Naturally, most people will just send another transaction, but that could result in 2 different transactions being sent. 

It would be cool if we could save transactions after sending them, so in the situation I described above, I could just save it, connect to another peer and send it again. Or an option to make the wallet broadcast the transaction to different peers.

**Comment by alexbarnsley** [comment]
This should already be possible. When a transaction is unconfirmed for 45 minutes, it will become "expired". That expired transaction when clicked allows for resending on whichever peer you're connected to:

![image](https://user-images.githubusercontent.com/8069294/50183563-6759b780-030a-11e9-8b2e-cc73023fcb66.png)

**Comment by vmunich** [comment]
I understand that this option shows up after 45 minutes, but what do you think about reducing that 45 minutes threshold to something quicker? Or a message like `You'll be able to resend this transaction after X minutes`. Since there's no feedback at this moment, I think most people will end up sending a second transaction.

**Comment by zillionn** [comment]
Hm, it looks like it'd be a very nice feature to be able to `DELETE` a transaction from the pool. Send some signed message with the `DELETE` request...

**Comment by doubled1c3** [comment]
I agree with Zillionn, that would be nice, although it sounds like a new transaction type- might be possible to work into Core 2.1

**Comment by vmunich** [comment]
That's unrelated to this issue. I'll close this issue as currently, nodes will reject transactions older than 45 minutes, rendering this feature request useless: https://github.com/ArkEcosystem/core/blob/master/packages/core-transaction-pool-mem/lib/defaults.js#L17
