### ISSUE TITLE
Added Wallets seen as compact cards

### ISSUE THREAD

**Issue by michaelthecryptoguy** [ArkEcosystem/desktop-wallet#798]
**Feature Request**
Added wallets are seen as compact cards

**Solution i'd like**
The ability to see the wallets as a list, rather than compact cards

**Comment by umhowdoidothis** [comment]
Second this.

**Comment by dated** [comment]
FYI i am working on this

**Comment by dated** [comment]
![image](https://user-images.githubusercontent.com/6547002/50373711-9494b700-05e3-11e9-81cd-26fbc279cacb.png)

WIP obviously.

**Comment by zillionn** [comment]
@dated Looks beautiful!

Can you also add a search field in the top right corner which will filter the results onkeyup/down? Same goes for the contacts.

**Comment by doubled1c3** [comment]
Looks good

**Comment by michaelthecryptoguy** [comment]
> FYI i am working on this

Thank You Dated!

**Comment by doubled1c3** [comment]
@dated in your WIP tabular view, possible to implement actions column with "copy to clipboard" and "delete" icons? Possible to make sure view preference is remembered for next application launch?

**Comment by dated** [comment]
The chosen layout is remembered and global for wallets and contacts. I'll change the delete column to actions and add a clipboard button, sounds good!

**Comment by dated** [comment]
The screenshot here is outdated, see the PR for a more recent one ;)

**Comment by doubled1c3** [comment]
@dated *Nice!*

**Comment by j-a-m-l** [comment]
Implemented in #852
