### ISSUE TITLE
Idea for Feature Request on Announcements Tab

### ISSUE THREAD

**Issue by michaelthecryptoguy** [ArkEcosystem/desktop-wallet#801]
**Feature Request**
After I have cycled through, all of the announcements (they have been clicked on with the (X), enable some type of recycle or re-sort of the announcements. Where the announcement will re-show/re-appear.

**Comment by alexbarnsley** [comment]
Clicking "X" on an announcement moves it to the bottom. Just scroll down and you can re-read
