### ISSUE TITLE
Announcements Tab

### ISSUE THREAD

**Issue by michaelthecryptoguy** [ArkEcosystem/desktop-wallet#802]
**Feature Request**
Instead of the red dot, perhaps have an exclamation mark as a notification for news.

**Comment by alexbarnsley** [comment]
What is the difference?

**Comment by dated** [comment]
The red dot is subtle enough to be noticed and not to be disturbing, an exclamation mark would be too big of an eye catcher for people not using the announcement tab.

**Comment by alexbarnsley** [comment]
Yes I agree. An exclamation mark implies it **needs** to be read
