### ISSUE TITLE
Increase Maximum of 50 tx’s per page

### ISSUE THREAD

**Issue by michaelthecryptoguy** [ArkEcosystem/desktop-wallet#804]
**Feature**
I would like to see an additional last transactions tab. As of now, I can only see the last (50) transactions

**Describe the solution you'd like**
On the wallet, where it shows last transactions. Add a row tab, to enable viewing more of the (last transactions)

**Comment by j-a-m-l** [comment]
You can use the button on the lower right corner to go to the next page.

**Comment by michaelthecryptoguy** [comment]
![untitled-4](https://user-images.githubusercontent.com/24502401/50553926-2012e580-0c7f-11e9-895c-dd5f411ed228.jpg)
Click where the red arrow is pointing.

**Comment by j-a-m-l** [comment]
So you want a page that list latest transactions of all wallets or adding pagination to the dashboard?

**Comment by michaelthecryptoguy** [comment]
Can we get an opinion from others within the community?

**Comment by dated** [comment]
I think that is a feature more suited for the explorer than the wallet, which has been partly discussed with Brian already. I'll go into more detail in a separate feature request (announcement).

**Comment by doubled1c3** [comment]
Hmm, latest transaction are latest transactions... it's primary use is to get a quick view on your address activity across all of recent time.  Does the request gather all transactions from all wallets and display a limited on homepage? or does it request a limited number in the first place? Will modifying the behavior stress peers more?

**Comment by Bluffet** [comment]
Personally, I don't like pagination for wallets. It makes it harder to find whatever you look for. It might take up more resources, but i don't care. 

At least to opt out of pagination would be nice.
