### ISSUE TITLE
Simplicity is gone with new wallet

### ISSUE THREAD

**Issue by michaelthecryptoguy** [ArkEcosystem/desktop-wallet#809]
**Is your feature request related to a problem? Please describe.**

Simplicity is gone with the new wallet. Create a second version desktop wallet, without current wallet design added features. Call it Ark-Lite Wallet. A simplified version of the Ark.io Desktop Wallet. 

I know this opens another can of worms, with the newest version being more newbie suitable But we must balance the cater of features, simplicity, and usability for the end users, both advanced, intermediate, and beginner.

**Comment by alexbarnsley** [comment]
IF we did another lite version, it wouldn't be part of this codebase, so this issue doesn't live here imo
