### ISSUE TITLE
Plug in system with the ability to add Bitcoin or Ethereum to the wallet

### ISSUE THREAD

**Issue by michaelthecryptoguy** [ArkEcosystem/desktop-wallet#812]
**Feature Request**

Plug in system with the ability to add Bitcoin or Ethereum to the wallet

**Comment by alexbarnsley** [comment]
There will be a plugin system and that's one of our major additions which will be next, once we've figured out how to do it securely. Whether it will be possible to add non-ARK chains won't be part of how we decide to write the plugin system and we won't specifically think about non-ARK chains integrations. If someone is able to write a plugin to do what you're asking, it shouldn't be included as an issue here as it will be a third-party plugin
