### ISSUE TITLE
Adding networks may seem to complicated to beginner

### ISSUE THREAD

**Issue by michaelthecryptoguy** [ArkEcosystem/desktop-wallet#813]
**Feature Request**
Adding networks may seem to complicated to beginner 

**Describe the solution you'd like**
Solution 1 – Add an “ARK” link that is adding the network

**Describe alternatives you've considered**
Have the networks in a list, where user can push a button for additional networks

**Comment by j-a-m-l** [comment]
Adding networks is something that beginners don't do.

Maybe changing the text form "Network overview" to "My networks" is clearer?

**Comment by michaelthecryptoguy** [comment]
I like that idea.

**Comment by alexbarnsley** [comment]
resolved in #821
