### ISSUE TITLE
Second Passphrase Creation Missing

### ISSUE THREAD

**Issue by KentHampton** [ArkEcosystem/desktop-wallet#830]
**Platform (please complete the following information):**

 - Version (e.g. Desktop Wallet 2.1.0)

**Describe the bug**
I'm sorry I cannot reproduce the error, if it truly is one.
When setting up my wallet I was very careful to record the twelve word pass phrase. After dismissing that I believe I was presented the opportunity to encrypt the passphrase, and it looked to be optional. I chose not to use encryption.
The wallet seems to be successfully created at that point and I successfully transferred ARK to the wallet.

When I try to vote for a delegate and click on vote, I am asked for my passphrase. The only passphrase I every received was the twelve word passphrase and that is not accepted as the passphrase here. I tried multiply times and I am sure the words are entered correctly.

I encounter the same problem if I try to transfer my ARK back to my an exchange.

I'm inclined to concluded the the proper passphrase as never generated and presented to me on creation of the wallet, or, there is an error preventing the twelve word passphrase from being accepted in these instances. 

**How to reproduce the bug**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Additional context**
Context about the problem here, such as screen resolution, error messages on the console (View > Toggle Developer Tools), or any other information that could be useful for reproducing and fixing the bug.

**Comment by dated** [comment]
For starters I would confirm that every word is spelled correctly, the word list can be found here https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

If all words check out, make sure you are typing in the passphrase as follows (the spaces are important)

`word1 word2 ... word12`

Maybe you wrote the words down in the wrong order? I believe they are presented to you in a grid layout when you first create a wallet.

**Comment by KentHampton** [comment]
Edgar,
 
 
Thank you for the word list. I was typing "identity" rather than "indentify".
 
I guess was not as careful as I thought. I appreciate your help.
 
Have a Merry Christmas!
 
 

Sincerely, Kent Hampton
President
The Sword of St. George, Inc.785-410-1373
 
 

 
 
 
 
 

-----Original Message-----From: "Edgar Goetzendorff" <notifications@github.com>Sent: Friday, December 21, 2018 8:00amTo: "ArkEcosystem/desktop-wallet" <desktop-wallet@noreply.github.com>Cc: "KentHampton" <kent@1791.com>, "Author" <author@noreply.github.com>Subject: Re: [ArkEcosystem/desktop-wallet] Second Passphrase Creation Missing (#830)

For starters I would confirm that every word is spelled correctly, the word list can be found here https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt
If all words check out, make sure you are typing in the passphrase as follows (the spaces are important)
word1 word2 ... word12
Maybe you wrote the words down in the wrong order? I believe they are presented to you in a grid layout when you first create a wallet.

**Comment by dated** [comment]
Glad you got it figured out!

Merry Christmas from _not yet a delegate [dated](https://arkdelegates.io/delegate/dated/)_
