### ISSUE TITLE
Ark pay doesn't create transaction window on ubuntu

### ISSUE THREAD

**Issue by moazzamak** [ArkEcosystem/desktop-wallet#834]
**Platform (please complete the following information):**
 - OS: Ubuntu 16.04
 - Version: Desktop Wallet 2.1.1

**Describe the bug**
Using the pay now button on ark pay opens/focuses the wallet but doesn't create the transaction window.

**How to reproduce the bug**
Steps to reproduce the behaviour:
1. Install latest wallet v2.1.1
2. go to https://arkecosystem.github.io/pay-demo-vue/
3. click on pay now
4. observe wallet

**Expected behaviour**
Transaction window should spawn with transaction details filled in.

**Screenshots**

**Additional context**
No errors show up on the console log. Filing the bug in desktop wallet repo since the wallet is being opened/focused so the ark: uri xdg-open call is working properly.

**Comment by j-a-m-l** [comment]
I've tried on Kubuntu 18.10 and it ask to open the wallet, but, after after opening it, the wallet doesn't show anything related to the transaction.
