### ISSUE TITLE
Transactions are sent to different peer

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/desktop-wallet#842]
**Platform (please complete the following information):**
 - macOS Mojave 10.14.2
 - Desktop Wallet 2.1.1

**Describe the bug**
I'm using custom peer `95.179.150.18:4003` and I'm pulling the data from it, but when I send a tx, it is sent to a different peer `167.114.29.34:4003`:

<img width="846" alt="1" src="https://user-images.githubusercontent.com/3462869/50372772-5bf1df00-05dd-11e9-9a7b-ec279553bcf1.png">
<img width="862" alt="2" src="https://user-images.githubusercontent.com/3462869/50372776-62805680-05dd-11e9-8920-621d4a92b856.png">
<img width="928" alt="3" src="https://user-images.githubusercontent.com/3462869/50372777-64e2b080-05dd-11e9-831e-4b9bce7c16e9.png">

I believe the problem is with `alternativeWallet`, it's always set in `onBuilt` and it should be set only when using ARK Pay and choose a wallet from different network:
https://github.com/ArkEcosystem/desktop-wallet/blob/c013b91f4e0c2b9907309ad4bb2937404b5c69bb/src/renderer/components/Transaction/TransactionModal.vue#L103-L107
https://github.com/ArkEcosystem/desktop-wallet/blob/c013b91f4e0c2b9907309ad4bb2937404b5c69bb/src/renderer/components/Transaction/TransactionModal.vue#L129-L138

**Expected behaviour**
To send the tx to the connected peer not select best/different peer.

**Comment by alexbarnsley** [comment]
resolved in #922
