### ISSUE TITLE
Avatar/Profile removal option

### ISSUE THREAD

**Issue by Litom** [ArkEcosystem/desktop-wallet#861]
It should be possible to remove the avatars. I don't want to see some ugly face in the bottom left corner of my wallet or anywhere else where it appears. Actually I don't even want those profiles.

There should be the option to just login using a private key/passphrase and then accessing the wallet without those features. And there should be the option to set a custom avatar or remove the standard one to have a profile without some weird avatar.

The old wallet was way better for that. There should be always the option to disable features that you add because otherwise its a downgrade for people who don't want those features.

**Comment by dated** [comment]
I highly disagree with what you say about the profiles. Imho they are an enhancement in every way. The old wallet did not allow you to logically separate addresses of the same network, they were all grouped under the same network. Now i can have my private addresses completely separated from the addresses used for my business or side projects and so on.

**Comment by Litom** [comment]
They are maybe an enhancement for you but not for me. I just want a simple functioning wallet without advanced and irritating features like having multiple addresses in profiles or profiles in general. Maybe its an enhancement for you in every way but not for me because I don't need the feature. Thats why I suggested this to have just the simple functionality of a classic wallet like it was in the old version.

**Comment by zillionn** [comment]
@Litom It's not possible to please 100% of the users. IMO most users, like me, like the new profiles and also this is the team's vision. If you don't like it/need a simple solution, just use the explorer:
https://explorer.ark.io/

**Comment by zillionn** [comment]
Maybe a solution could be a default `ARK Mainnet` profile when you install the app. So you just add your wallet. And if you don't like the default settings you can always edit the profile.

**Comment by Litom** [comment]
Why should I use the explorer? The explorer is not a wallet.

**Comment by j-a-m-l** [comment]
We are going to support custom avatars. When that is added, you could use the wallet with 1 profile, with an empty avatar.

**Comment by doubled1c3** [comment]
I know this issue is closed and while I agree with @zillionn and @dated , the issue with the profiles is the linking of exactly 1 network to 1 profile, forcing multiple profiles to be created for one "person." So today I will be detailing a new github issue regarding profiles <> networks and how they relate and architecture slightly adjusted to please everyone in the community
