### ISSUE TITLE
Ledger Passphrase required & duplicate wallet in wallet list

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/desktop-wallet#879]
Reported by @alessiodf (fun)

**Platform (please complete the following information):**
 - OS: macOS
 - Version 2.1.1

**Describe the bug**
When there's a wallet imported through address-only import, it shows on the wallet list. If this is a ledger wallet and the ledger device is plugged in, it shows the wallet twice in the wallet list. It also seems to request a passphrase when trying to send from this ledger wallet.

A workaround is to remove the address-only wallet. If needs be it can be added as a contact for now.

**How to reproduce the bug**
Steps to reproduce the behaviour:
1. Go to Wallet Import
2. Click on Address Only import and enter a ledger address
3. Complete import
4. Plug in ledger

**Expected behaviour**
Ledger wallet should only be shown once on the wallet list, so the list needs merging by address. Also, the ledger wallet should never ask for a passphrase.

**Comment by alessiodf** [comment]
Also worth mentioning that the ledger wallet's name takes priority over the address-only wallet's name and consequently both wallets get renamed to the ledger wallet's name when it's plugged in.

**Comment by alessiodf** [comment]
OK I can reproduce this bug even without importing an address-only wallet:

1. Add a non-ledger wallet address (can be a new one)
2. Follow a link using the AIP13 schema to pay for anything using Ark e.g. the Arkland raffle (note the Ark Pay demo on devnet does not appear to be affected by this bug)
3. It will, by default, select the non-ledger wallet to send the transaction and prompt for a passphrase
4. Changing to the sender wallet to the ledger still prompts for a passphrase

Removing the non-ledger wallet and trying again works fine.
