### ISSUE TITLE
URL scheme

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/desktop-wallet#886]
OS: macOS Mojave 10.14.2

I've been experiencing this issue for a long time but forgot to report it.

Not sure if the problem is with the Ark app/Electron generally or the Persona version, but when I open the Persona Desktop Wallet v1.5.5 it removes Ark app as the default app for `ark:` URLs. I even tried reinstalling the Persona app but no luck.

So this is how it looks if the last opened app is Ark Desktop Wallet:
<img width="780" alt="screenshot 2018-12-29 at 10 48 20" src="https://user-images.githubusercontent.com/3462869/50535894-50f7fb00-0b57-11e9-9b13-1e8eeb909c09.png">
<img width="780" alt="screenshot 2018-12-29 at 10 48 26" src="https://user-images.githubusercontent.com/3462869/50535896-52c1be80-0b57-11e9-83b2-ade027368dae.png">
<img width="780" alt="screenshot 2018-12-29 at 10 48 31" src="https://user-images.githubusercontent.com/3462869/50535899-56eddc00-0b57-11e9-9f8f-e8fd3763ee9d.png">
<img width="780" alt="screenshot 2018-12-29 at 10 48 37" src="https://user-images.githubusercontent.com/3462869/50535900-58b79f80-0b57-11e9-8510-245069ff7b6e.png">

And this is after I open the Persona Desktop Wallet:
<img width="780" alt="screenshot 2018-12-29 at 10 49 53" src="https://user-images.githubusercontent.com/3462869/50535916-7dac1280-0b57-11e9-8074-1752dc43aaaa.png">
<img width="780" alt="screenshot 2018-12-29 at 10 49 48" src="https://user-images.githubusercontent.com/3462869/50535918-83a1f380-0b57-11e9-80d7-a3a83c2df1f3.png">

If I open the Ark app after that, it fixes the URL scheme.

**Comment by alexbarnsley** [comment]
This is a Persona issue I guess, they need to change the URI here: https://github.com/PersonaIam/persona-wallet/blob/4ef45ed9784e464fbda966ff1c9059fe3e540dd0/main.js#L264
