### ISSUE TITLE
Globalize "Display number of rows" and Introduce Memory

### ISSUE THREAD

**Issue by doubled1c3** [ArkEcosystem/desktop-wallet#895]
**Problem**

Whenever viewing a transaction list for a specific wallet address, there is a "Display number of rows" item with a dropdown (default is 10 rows)

This functionality is not shared when moving from wallet A to wallet B, it just goes back to 10.

This functionality is not remembered on next launch.

**Solution**

First, remove the feature from the wallet screen and move it to the Gear menu. There, place "Show rows count" variable with dropdown of the numbers (10,20,30,40,50)

Next, add the variable to the others that are remembered on next launch (like dark mode variable).

Finally, display the appropriate number of rows for all wallet addresses across all networks and profiles, according to the global variable.

**Comment by dated** [comment]
I don't necessarily agree with adding that setting to the settings menu, as it's specific to the wallets transaction table only. It should however be remembered, working on that now.

**Comment by zillionn** [comment]
I guess just remembering it will solve all the issues...

**Comment by alexbarnsley** [comment]
Resolved in #896
