### ISSUE TITLE
no hover on confirm delete

### ISSUE THREAD

**Issue by michaelthecryptoguy** [ArkEcosystem/desktop-wallet#906]
**Platform (please complete the following information):**
 - OS: Windows 7
 - Version 2.1.1

**Describe the bug**
When you are ready to delete a wallet the action on the right doesn't hoover

**How to reproduce the bug**
Steps to reproduce the behaviour:
1. Create Wallet, with passphrase
2. Click on delete wallet
3. Click on right side (marked in red)

**Expected behaviour**
Mouse should show hover option 
![desktop_wallet_confirm](https://user-images.githubusercontent.com/24502401/50552386-09a96180-0c60-11e9-8af8-a1098805aacb.jpg)

**Comment by ItsANameToo** [comment]
It does show different styling on hover:

Default:

<img width="233" alt="schermafbeelding 2018-12-31 om 10 46 22" src="https://user-images.githubusercontent.com/35610748/50557869-74eb4600-0ce9-11e9-81b4-0ac74b3d8c60.png">

Hover:

<img width="209" alt="schermafbeelding 2018-12-31 om 10 46 27" src="https://user-images.githubusercontent.com/35610748/50557867-74eb4600-0ce9-11e9-8f5d-c67f294545b2.png">
