### ISSUE TITLE
Verify Timedate Status & Add 24h/12h Preference

### ISSUE THREAD

**Issue by doubled1c3** [ArkEcosystem/desktop-wallet#908]
Verify timedate status. Is the desktop showing timedates in local system time, or always GMT? If always GMT make local system time.

Also let's add a preference in the gear menu for "Use 24h time format" with switch, so if 12h time format is desired, it can be used. I noticed that the explorer shows 12h time format, so desktop wallet should be consistent

**Comment by alexbarnsley** [comment]
The transaction list date/times are in 24h format in order to save space. Might not seem like much but those 3 characters are worth it when looking at the main dashboard screen.

**Comment by ItsANameToo** [comment]
There will be a setting in the profile where you can choose `default` (whatever your locale specifies), `12h` and `24h` formats

**Comment by doubled1c3** [comment]
Thanks for executing. The mobile wallet is 12h which is really nice, so having 12h option in desktop wallet is good. @alexbarnsley if space is an issue on the dashboard latest transactions, I do recommend the transaction ID column be reworked according to #907 item 1. Because the dashboard latest transaction list is showing from multiple wallets, I do not recommend applying additional changes detailed in #907 , just item 1. This will save some space and remove some clutter in the table view of dashboard, removing the "12h time 3 character" issue.
