### ISSUE TITLE
Sent transaction is shown as received instead of sent until wallet is refreshed

### ISSUE THREAD

**Issue by vmunich** [ArkEcosystem/desktop-wallet#923]
**Describe the bug**

When I send a transaction, and it confirms, it's shown on the transactions list as a received transaction (in green), until I refresh the transactions list.

**Screenshots**
Easier to explain with a GIF:

![](https://i.gyazo.com/75c1e8695c85c92f3f8d46c255ce8043.gif)

**Environment**
- OS: OSX 10.14
- Ark Desktop Wallet 2.1.1

**Comment by vmunich** [comment]
https://github.com/ArkEcosystem/explorer/issues/537

**Comment by dated** [comment]
I started working on this, the problem is that the helper fields such as `isSender` are not applied to transactions fetched from the store.
