### ISSUE TITLE
Ledger wallets won't update their balances, blocking sending funds

### ISSUE THREAD

**Issue by vmunich** [ArkEcosystem/desktop-wallet#925]
**Platform (please complete the following information):**
 - OS: OS X 14.0
- Version: 2.1.1

**Describe the bug**
My ledger wallets have the same balance for days on the wallet, even though their balance has changed. I have tried disabling and re-enabling ledger caching, refreshing transactions, changing peers. Balances won't update:

![](https://i.gyazo.com/9a3308909c8862f9867a902ec5dfb8f2.png)

The problem though, is that this blocks sending funds. My wallet's balance is now higher than the balance that my wallet is stuck with, and I can't send more ARK than the stuck balance:

![](https://i.gyazo.com/56cb2fb279cf16611c9d7f050b704058.png)

**Comment by vmunich** [comment]
Disabling `Cache ledger wallets?` and restarting the wallet temporarily fixed the issue.

**Comment by alexbarnsley** [comment]
should be resolved with #926
