### ISSUE TITLE
Ledger white screen with old firmware

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/desktop-wallet#940]
**Platform (please complete the following information):**
 - OS: Windows 7
 - Version: Ark.Desktop.Wallet-x64-2.1.1

**Describe the bug**
I've tried to switch votes on my friend's old and slow laptop and when connecting the Ledger and choose `Ark` app, `v2.1.1` shows a white screen and the app is unresponsive. Using `v1.6.1` the Ledger is working and loading the wallets, but when I try to unvote it shows an error message like:
`Can not find delegate "xxx"`

![win7](https://user-images.githubusercontent.com/3462869/50735888-33add700-11be-11e9-8761-5243dec7e874.jpg)
![v2-wallets](https://user-images.githubusercontent.com/3462869/50735899-50e2a580-11be-11e9-9c96-9195f926a50b.jpg)
When select the `Ark` app on the Ledger:
![white-screen](https://user-images.githubusercontent.com/3462869/50735903-5dff9480-11be-11e9-9cae-bb9d08f638b8.jpg)

**Comment by j-a-m-l** [comment]
I've tried on a Windows 7 VM and the Ledger works fine and I can vote and unvote.

I've tried quitting the Ledger app while the desktop wallet is running and enabling it again, and in this case, the desktop wallet works normally, but it needs like 2-4 seconds to recognize the Ledger again (no blank screen is displayed).

Could you add more information about the problem?

**Comment by zillionn** [comment]
I found out what was the problem, it wasn't the Windows. The problem was the Ledger firmware `1.4.1` and after updating to `1.4.2` everything is working.
