### ISSUE TITLE
The WalletNew refresh action makes the page shake

### ISSUE THREAD

**Issue by JeremiGendron** [ArkEcosystem/desktop-wallet#944]
**Describe the bug**
Because the wallets get deleted from `this.wallets`, there's no rendering of the width and depth-adding elements which are normally there; this causes the right side of the page to jerk up and down abruptly.

**How to reproduce the bug**
Steps to reproduce the behaviour:
1. Go to 'Create new wallet'
2. Click on 'The refresh button'
4. See page shake

```diff
- This doesn't occur on smaller screen sizes
```

**Expected behaviour**
No abrupt movement on the screen

**Screenshots**
![walletnew_reload-bug](https://user-images.githubusercontent.com/23587429/50777511-d0797e80-1269-11e9-9497-e8ce7c2f2b9e.gif)

**Comment by j-a-m-l** [comment]
@JeremiGendron this should have been fixed on the latest version. Would you mind to try it and confirm that it does?

**Comment by JeremiGendron** [comment]
@j-a-m-l all good!
