### ISSUE TITLE
Failed to decrypt passphrase while trying to vote for a delegate

### ISSUE THREAD

**Issue by zaderak** [ArkEcosystem/desktop-wallet#946]
**Platform (Desktop Wallet on Yosemite Imac mid 2007):**
 - OS: [OS X 10.10.5]
 - Version (Desktop Wallet v2.1.1)

**Describe the bug** I don't know if it's a bug,but I've search everywhere for an answer and I don't see anyone else posting about this

**How to reproduce the bug**
Steps to reproduce the behaviour:
1. Go to 'once in Wallet Button in Desktop...'
2. Click on 'Delegates'
3. Choose Delegate.."Quarkpool".'
4. Click on "vote"
5. Select Transaction fee "adjust to above average ".2786...
6. input passphrase into encryption password selection
7. push "next" button

8. get "failed to decrypt passphrase" after 5 to 10 second wait 

**Expected behaviour**
vote to go through

**Screenshots**
doesnt let me screen shot

**Additional context**
thats it

**Comment by zillionn** [comment]
You're asked for your `encrypted password` not for your `passphrase`. When you were creating your account, you've set an encrypted password for faster signing of the transactions.

**Comment by alexbarnsley** [comment]
@zillionn is correct. When importing the wallet you will have set a password to encrypt your wallet. This is so your passphrase isn't needed to send a transaction, just the password you chose. If you've forgotten your password you can delete the wallet and reimport using the passphrase, although maybe try importing first to be sure you are 100% sure the passphrase is correct (it will tell you the wallet is already imported).

**Comment by alexbarnsley** [comment]
Regarding screenshot, the app is protected. You can disable it in the setting menu (cog icon) on the left and turn off "Screenshot protection". It will be re-enabled when you reload the app.
