### ISSUE TITLE
Show the price and time tooltip when mousing over the MarketChart

### ISSUE THREAD

**Issue by JeremiGendron** [ArkEcosystem/desktop-wallet#951]
**Is your feature request related to a problem? Please describe.**
It is not convenient to have to track the LineChart's line to get more precise pricing info.

**Describe the solution you'd like**
The tooltip that appears when on the line to be displayed relative to the mouse's position on the x-axis

**Describe alternatives you've considered**
I've tried to implement a vertical line mapping to the time as well, but was unsuccessful with vue-chartjs plugins.

**Additional context**
Current:
![marketchartbefore](https://user-images.githubusercontent.com/23587429/50981649-737c0380-14c9-11e9-9945-b751500f8463.gif)

**Comment by alexbarnsley** [comment]
Resolved in #973
