### ISSUE TITLE
Make it possible to update wallet names in the list view

### ISSUE THREAD

**Issue by boldninja** [ArkEcosystem/desktop-wallet#983]
**Is your feature request related to a problem? Please describe.**

With the introduction of the list view, we can take the advantage of some of the configuration options for the wallet in that view to save on loading each wallet separately by having an option to update some of the stuff in list view, saves you on API calls if you wanna do mass updates + on clicks. 

**Describe the solution you'd like**
Have a simple tag (like with delete icon) when you click on it to have an option to rename wallets on the go. Can be useful for contacts as well.

**Additional context**

![editnames](https://user-images.githubusercontent.com/25795454/51316288-83a95b00-1a54-11e9-863e-b131d7fc6c8a.jpg)

**Comment by boldninja** [comment]
@dated something for you maybe?

**Comment by j-a-m-l** [comment]
It could probably be done on the normal view.

An alternative is clicking on the name to edit it, or adding a edit icon near the name to change it to edition mode, the same way that profile edition has a way to update its name.

**Comment by boldninja** [comment]
Yeah whatever works better.

**Comment by dated** [comment]
yea, i'd convert the current `delete` column to a `action` column which can host more buttons, e.g. `edit`.

**Comment by boldninja** [comment]
:+1:

**Comment by alexbarnsley** [comment]
Resolved in #985
