### ISSUE TITLE
Help to see back ARK

### ISSUE THREAD

**Issue by finoho78** [ArkEcosystem/desktop-wallet#990]
Few month ago i kept about 378 Ark on NANO S .Nano firmware 1.4.2 and i can login to see ARK on ARK Client (version 1.5.1)
Then i removed ARK app on NANO to upgrade Nano to newest firmware (1.5). and reinstalled ARK app
And connect Nano ledger to ARK client, it is NOT connect together (already try to put Browser YES/NO). if browser YES--->Ark client stop working, if browser NO-->Ark client pending forever
i already try login Nano to Ark desktop wallet but look like it not support the nano s
please help to get back Ark.Thank

**Comment by alexbarnsley** [comment]
Hi. There was a tweet we sent out about this. Ledger have unfortunately uploaded an old version of the Ark app to their ledger store (0.1.2). This doesn't seem to work with our wallet but we're working with them to get that fixed. I will close this issue as it's not desktop related but keep an eye out on our Twitter or Slack as we'll let people know when it is resolved. Thank you.
