### ISSUE TITLE
Can't properly select balance in wallet view

### ISSUE THREAD

**Issue by Azure-Infinity** [ArkEcosystem/desktop-wallet#993]
**Platform (please complete the following information):**
 - OS: Windows 7
 - Version: Desktop Wallet 2.2.0 (existed with previous V2 wallets)

**Describe the bug**
The wallet ID icon (not the avatar) seems to be getting in the way while trying to select your balance or address.

**How to reproduce the bug**
Steps to reproduce the behaviour:
1. Open ARK Desktop Wallet.
2. Click the "My Wallets" icon on the left side.
3. Click on any of your wallets.
4. Try to manually select your total balance or ARK address on the top.

**Expected behaviour**
I expect to be able to manually highlight my ARK address and also my total ARK balance without making the wallet select everything.

**Screenshots**
![capture](https://user-images.githubusercontent.com/46818126/51391700-ac9c1f80-1b2a-11e9-895e-16dd26c938f1.JPG)

**Comment by j-a-m-l** [comment]
@Azure-Infinity I've changed, on #994, the text to be selectable (part of other widget was hiding the text).
