### ISSUE TITLE
Wallet names/sorting

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/desktop-wallet#997]
1. I have many Ledger wallets added as Watch-Only and named 1, 2, 3..., 10, 11, 12. On the `Wallets` page they are not sorted correctly but 1, 10, 11, 12, 2, 3...

2. When I connect my Ledger, in the `Wallets` page  I see this nice red Ledger badge:
<img width="164" alt="screenshot 2019-01-19 at 12 50 27" src="https://user-images.githubusercontent.com/3462869/51425751-e4699c80-1be8-11e9-9380-ad31d57c9fb2.png">

But when inside some wallet, there is no such badge but the word `Ledger` is added to the wallet name and I'm confused which is a Ledger wallet and which is not:
<img width="160" alt="screenshot 2019-01-19 at 12 50 49" src="https://user-images.githubusercontent.com/3462869/51425761-f4817c00-1be8-11e9-9395-6ae59fe719c2.png">
Same goes for the `Dashboard`.

Also maybe not a bad idea, when on `Wallets` page, to sort all Ledger wallets on the top and then the regular wallets like on the other places.

**Comment by zillionn** [comment]
IMO the best approach when Ledger is connected, is to remove all duplicate wallets and leave only the Ledger once.

**Comment by dated** [comment]
I'll add these changes to #991.

**Comment by zillionn** [comment]
Not sure if intentional, but `Wallets` and `My contact` pages doesn't remember the sorting:
- wallets `listview` - always sorted by `Balance` desc
- wallets `card/grid view` - always by name asc
- contacts - always by name asc

IMO you should remember the user's choice and sort them that way everywhere.

**Comment by dated** [comment]
FYI #1002
